### ISSUE TITLE
Bug: Cordova does not set minSdkVersion according to preference in config.xml

### ISSUE THREAD

**Issue by JonatanWigstrom** [apache/cordova-android#892] opened 2020-01-09 10:20 UTC
# Bug Report

## Problem
After setting the android-minSdkVersion preference in config.xml, the APK is built with a higher minSdkVersion than specified.

### What is expected to happen?
The APK should be built with minSdkVersion set to 24

### What does actually happen?
The APK is built with minSdkVersion set to 26

### Command or Code
Config.xml (Irrelevant sections excluded):
```xml
<widget android-versionCode="10001" defaultlocale="sv-SE" id="*" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:android="schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0" xmlns:vs="http://schemas.microsoft.com/appx/2014/htmlapps">
  <platform name="android">
    <allow-intent href="market:*" />
  </platform>
  <platform name="android">
    <preference name="android-minSdkVersion" value="24" />
    <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
      <application android:usesCleartextTraffic="true" />
    </edit-config>
  </platform>
  <plugin name="cordova-plugin-whitelist" version="1.3.3" />
  <plugin name="cordova-plugin-camera" version="3.0.0" />
  <plugin name="cordova-plugin-inappbrowser" version="1.2.1" />
  <plugin name="cordova-plugin-splashscreen" version="3.1.0" />
  <plugin name="cordova-plugin-geolocation" version="2.1.0" />
  <plugin name="cordova-plugin-vs-taco-support" version="0.2.3" />
  <plugin name="cordova-plugin-customurlscheme" src="https://github.com/EddyVerbruggen/Custom-URL-scheme" version="4.3.0">
    <variable name="URL_SCHEME" value="iol" />
  </plugin>
  <plugin name="cordova-plugin-qrscanner" spec="^2.6.0" />
  <plugin name="cordova-plugin-insomnia" src="https://github.com/EddyVerbruggen/Insomnia-PhoneGap-Plugin" version="4.3.0" />
  <engine name="android" spec="^8.0.0" /> 
</widget>
```

### Environment, Platform, Device
Platform: Android

### Version information
Cordova-android: 8.0.0
Cordova-cli: 9.0.0
Cordova-plugins:

- cordova-plugin-whitelist: 1.3.3
- cordova-plugin-camera: 3.0.0
- cordova-plugin-inappbrowser: 1.2.1
- cordova-plugin-splashscreen: 3.1.0
- cordova-plugin-geolocation: 2.1.0
- cordova-plugin-vs-taco-support: 0.2.3
- cordova-plugin-customurlscheme: 4.3.0
- cordova-plugin-insomnia: 4.3.0
- cordova-plugin-qrscanner: 2.6.0

OS: Windows 10
IDE: Visual Studio 2017

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by timbru31** [comment] 2020-01-09 11:32
This is a duplicate of #599

**Closed by timbru31** 2020-01-09 11:32 UTC
