### ISSUE TITLE
No scrollbars on elements with overflow: scroll

### ISSUE THREAD

**Issue by foofel** [apache/cordova-android#976] opened 2020-05-15 14:51 UTC
# Bug Report

### What is expected to happen?
having a div with overflow:scroll thould show scollbars when the childen exceed the parent element size and allow scrolling

### What does actually happen?
scrolling works as ecpected but the scollbars are hidden

### Command or Code
1. follow the guide to create a testapp https://cordova.apache.org/docs/en/latest/guide/cli/
2. paste the code from the pastebin into the index.html https://pastebin.com/68D41N0J
3. run the app

### Environment, Platform, Device
reproduced on: 
- htc 10 (andriod 8.0) with chrome 81 and 
- pixel3 emulator with api 29 and android 10

the same code from the pastebin works correctly directly in the chrome mobile browser

### Version information
9.0.0 (cordova-lib@9.0.1)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2020-05-28 02:38
I've reproduced this on my phone, running chrome webview 81, android 10, target API 28 (latest cordova versions).

Same behaviour with `overflow: auto`.

Although I question if this is an actual bug inside cordova, or if it's a bug in the webview. Do note that the android webview doesn't necessarily equal the chrome browser app. There are two different builds afterall. I'll still attach the bug ticket for now.

**Comment by patrick-entinux** [comment] 2020-05-29 01:48
Just want to add, I experienced this issue in a cordova project recently, had a scrolling div area and could not figure out how to get a scrollbar to show to indicate to the user that it was scrollable.

I did some research previously and found an old cordova plugin that claims to fix the issue:

https://github.com/mayflower/cordova-android-scrollbar/blob/f44e7cca0c98fb9d2cb6333225725eb98eac1259/src/android/AndroidScrollbar.java#L78

(Note: I have not tested it.)

Based on that, I think the scrollbar hiding is set here in the cordova-android code:

https://github.com/apache/cordova-android/blob/46a036ef265951d5371936b37d7296fa47fb28ce/framework/src/org/apache/cordova/engine/SystemWebViewEngine.java#L148

Not sure about the purpose, but it does seem like a specific configuration of cordova-android.

We ended up solving the problem in HTML by using a plugin called [OverlayScrollbars](https://github.com/KingSora/OverlayScrollbars), maybe it's a possible alternative too.

**Comment by breautek** [comment] 2020-05-29 13:15
Thanks, this is extremely helpful!

That line looks like it was added since the initial implementation of that class. Not sure the reasoning, but it's been 5 years.

https://github.com/apache/cordova-android/commit/087ec11e6abc61acde4e2860f8ee363f3daba578

If turning this to true fixes this issue, I'd support the PR.

**Comment by breautek** [comment] 2020-06-05 03:59
So I understand why `webView.setVerticalScrollBarEnabled(false);` was used...

This method is a `View` method, it's not related to webview. So it only provides enables the scrollbar on the root view. It has a side effect of it appearing to work when scrolling the document but If you have inner scrollable children in your HTML for example, you still have missing scrollbars.

Using the `::-webkit-scrollbar` css does work, it just seems like chrome webview has a different set of user agent styling than the chrome android browser. :confused:

**Comment by breautek** [comment] 2020-08-11 01:43
I'll be closing this because this isn't really a bug that is solvable by Cordova.

The workaround posted above works, but a true fix is going to need to come from upstream from Google. If this issue is significant enough for you, then I would report the bug with Chromium team.

**Closed by breautek** 2020-08-11 01:43 UTC
Labels: bug

**Comment by RandomEngy** [comment] 2023-01-01 17:19
The [bug finally got reported on Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1327047). You can star it over on their tracker to help get more attention.

It looks like they disabled rendering scrollbars so the root browser scrollbar wouldn't fight with the Android scrollbar, but that disabled *all* scrollbars.
