### ISSUE TITLE
Cordova Interface changes on 9.1.0

### ISSUE THREAD

**Issue by CharlesJQuarra** [apache/cordova-android#1225] opened 2021-05-01 15:44 UTC
I am using Cordova-android plugin from a Vue.js application. In cordova version 9.0.0, the `cordova` object had the following keys:

```
console.log(`{Object.keys(cordova)}`)
output:
define,require,version,platformVersion,platformId,addWindowEventHandler,addStickyDocumentEventHandler,
addDocumentEventHandler,removeWindowEventHandler,removeDocumentEventHandler,getOriginalHandlers,
fireDocumentEvent,fireWindowEvent,callbackId,callbacks,callbackStatus,callbackSuccess,callbackError,
callbackFromNative,addConstructor,exec,plugins
```

On version 9.1.0, this interface object has some important differences:

```
console.log(`{Object.keys(cordova)}`)
output:
define,require,version,platformVersion,platformId,addWindowEventHandler,addStickyDocumentEventHandler,
addDocumentEventHandler,removeWindowEventHandler,removeDocumentEventHandler,getOriginalHandlers,
fireDocumentEvent,fireWindowEvent,callbackId,callbacks,callbackStatus,callbackSuccess,callbackError,
callbackFromNative,addConstructor
```

As you can see, the objects `exec` and `plugins` are absent, which is how we interact with native components

Btw, the upgrade I did was as simple as doing `cordova platform remove android` and `cordova platform add android@9.1.0` and rerunning the same codebase

**Comment by breautek** [comment] 2021-05-01 16:14
![Screenshot from 2021-05-01 13-12-03](https://user-images.githubusercontent.com/11200662/116788241-eafd4480-aa7e-11eb-96f7-ea5e7ac2107c.png)

I'm not seeing the problem on my end. Are you able to reproduce in a simple cordova application (without the use of frameworks or third-party plugins)?

**Comment by breautek** [comment] 2021-09-13 01:20
Closing due to staleness.

**Closed by breautek** 2021-09-13 01:20 UTC
