### ISSUE TITLE
cordova prepare throw exception

### ISSUE THREAD

**Issue by AlessandroMetta** [apache/cordova-android#1675] opened 2023-10-17 15:51 UTC
> cordova prepare
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('MODULE_NOT_FOUND')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at C:\Users\alessandro.metta\AppData\Roaming\npm\node_modules\cordova\bin\cordova:32:22

**Comment by breautek** [comment] 2023-10-17 15:53
what's your node version?

**Comment by AlessandroMetta** [comment] 2023-10-18 07:41
> what's your node version?

v20.8.0

**Comment by breautek** [comment] 2023-10-18 12:03
I've installed and tested v20.8.0 specifically and unable to reproduce the issue in any of my projects and I also ran all the unit tests and they pass successfully.

There isn't really enough information to act on, so I'm closing this issue.

If you're affected by this issue, please create a new issue with the issue template filled out.

Including the log output of `--verbose` (e.g. `cordova prepare android --verbose`) may also provide information.

**Closed by breautek** 2023-10-18 12:03 UTC

**Comment by AlessandroMetta** [comment] 2023-10-18 13:39
thanks @breautek , --verbose revealed that it failed while executing before_prepare.js, as some npm dependancies were missing

**Comment by kuanyui** [comment] 2024-09-06 05:47
Also encountered exactly the same error message, platform

- Linux
- `node` 20.03
    - `cordova` 12.0.0
- `openjdk` 21.0.4 
    - `gradle` 8.10
    - `android-studio` 2024.1.2

Create project via
```sh
cordova create myapp
cd myapp
cordova platform add android
cordova run --emulator
```

And finally found the reason in this issue https://github.com/apache/cordova-android/issues/1717 --- that it's necessary to **manually startup** an Android emulator in Android Studio (`Android Studio -> (right sidebar) Running Devices`) before running `cordova run --emulator`.

**Comment by moianra23** [comment] 2025-03-20 07:50
Updating to Command Line Tools 19 fixed this for me. I had version 17 before.
