### ISSUE TITLE
A 'compile' is obsolete error 

### ISSUE THREAD

**Issue by Technikoc** [apache/cordova-android#1436] opened 2022-05-23 18:23 UTC
# Bug Report
I was having a build ready for my app and just updated my files inside it till now.
My last update was at the end of March.
Before some days i tried to update some js, css files and it just doesnt want to build.

## Problem
my problem all is written in this link and i can rewrite it here if it is needed
https://stackoverflow.com/questions/72350539/cordova-build-android-compile-is-obsolete-and-has-been-replaced-with-implemen

As far as i remember i dont update any stuff when my app is builded correctly exactly for that reason.
Since it is not needed i just upate my js,css and other files but it may have update something that i dont know.

### What is expected to happen?
To build as it was building till end of March :)

### What does actually happen?
Something is asking for something to be changed and i really dont know and dont want to if it is not needed cause my app was working fine and i want to revert the changes made after the end of March

Thanks for any help given and sorry for being such a wrong on this github but i am really newbie on these stuff and cordova 

## Checklist

- [ x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by breautek** [comment] 2022-05-23 18:48
Cordova generally doesn't support older releases.

Older releases are primarily discontinued when Google updates their required target sdk for the Google Play store. For this reason I'm closing this issue.

I can give a couple of recommendations however:

Test with a sample cordova app with no plugins installed. Do you observe the issue? If not, then one of your plugins is the cause. You can add them 1 by 1 to determine which plugin is the culprit.

If you do, observe the issue with the barebones app, then it's likely a native dependency updated. If you cannot upgrade, then you're option is to fork the android platform and make the required changes.

**Closed by breautek** 2022-05-23 18:48 UTC

**Comment by Technikoc** [comment] 2022-05-23 20:11
thank you for you reply and for the recommendations, much appreciated.
Yes i used a new clean project to check as you said and it shows me all these errors and warnings without any plugin, just adding the android platform and building as is.

I am not distributing my app to google play store.
I just export and then signed the apk standalone.
Is there any way to use my own build as it was since i am not in need of google play? 

The app is not just a personal, many users use it and i need somehow to be able to update the files in it.
Any possible solution would be very helpful!

**Comment by breautek** [comment] 2022-05-23 23:30
> Is there any way to use my own build as it was since i am not in need of google play?

It's very likely a native dependency declared in gradle that isn't quite limiting the version (or it could also be gradle itself).

If the source is inside cordova android, then you can fork the repository and branch off the 9.x release tag to correct the issue. And `npm pack` it to obtain the tgz file, which is installable in your project.

**Comment by Technikoc** [comment] 2022-05-24 12:42
thank you very much for your time and replies! i will do my best to solve it.

**Comment by breautek** [comment] 2022-05-24 12:55
I was mostly mobile yesterday so I couldn't provide our slack link, but now I'm back in the office, you can try asking our [slack](https://join.slack.com/t/cordova/shared_invite/zt-z70vy6tx-7VNulesO0Qz0Od9QV4tc1Q) community as well.

**Comment by Technikoc** [comment] 2022-05-25 14:28
Thank you for the link but i dont have many hours every day for this app (cause of my work) and i would really need any help provided through here better for me and whenever someone can give a hand.

I opened the previous working version of apk and checked some versions inside and i opened the nre with errors (it builds the release but it cannot be installed)

Here are the versions i found till now 
# Android Version 
var PLATFORM_VERSION_BUILD_LABEL = '9.1.0';

# Gradle version (META-INF\MANIFEST.MF)
Manifest-Version: 1.0
Built-By: Generated-by-ADT
Created-By: Android Gradle 4.0.0

Both apk`s previous and the fault one has the same versions and i dont know what the problem is.
----- I am using at enviroment path of windows :
c:\gradle-6.9.1\bin

----- inside gradle.build i have 
buildscript {
    ext.kotlin_version = '1.3.50'
    apply from: 'repositories.gradle'
    repositories repos

    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    apply from: 'repositories.gradle'
    repositories repos

    project.ext {
      defaultBuildToolsVersion="29.0.2" //String
      defaultMinSdkVersion=22 //Integer - Minimum requirement is Android 5.1
      defaultTargetSdkVersion=29 //Integer - We ALWAYS target the latest by default
      defaultCompileSdkVersion=29 //Integer - We ALWAYS compile with the latest by default
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

------ In the gradle-wrapper.properties 
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https://services.gradle.org/distributions/gradle-6.5-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists


------ As a build.wrapper says 
task wrapper(type: Wrapper) {
    gradleVersion = '6.5'
}


i can give lines of my files from my previous working apk and the fault apk if somehow can be helpfull for someone who knows what to do and give me a hand once a day or days cause i really need to fix and be able to update my app files.

Thank you in advance
