### ISSUE TITLE
Update Cordova Android 12.0-

### ISSUE THREAD

**Issue by vladortegab** [apache/cordova-android#1659] opened 2023-09-04 04:38 UTC
# Feature Request
I try to load the application with the cordova run command, and the application installs on the cell phone but it does not open, it is an application that I am updating the Android, I passed the files from the www folder, I installed the plugins one by one, but even so it does not work
## Motivation Behind Feature

2023-09-03 23:33:37.113 31509-31509 AndroidRuntime          co.com.prueba                        D  Shutting down VM
2023-09-03 23:33:37.113 31509-31509 QarthLog                co.com.prueba                        I  [PatchStore] createDisableExceptionQarthFile
2023-09-03 23:33:37.114 31509-31509 QarthLog                co.com.prueba                        I  [PatchStore] create disable file for co.com.prueba uid is 10468
2023-09-03 23:33:37.124 31509-31509 AndroidRuntime          co.com.prueba                        E  FATAL EXCEPTION: main
                                                                                                    Process: co.com.prueba, PID: 31509
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{co.com.prueba/co.com.prueba.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8668)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
                                                                                                    	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:187)
                                                                                                    	at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:110)
                                                                                                    	at org.apache.cordova.PluginManager.init(PluginManager.java:98)
                                                                                                    	at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:119)
                                                                                                    	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:156)
                                                                                                    	at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:234)
                                                                                                    	at co.com.prueba.MainActivity.onCreate(MainActivity.java:40)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8214)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8202)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                                                    	at android.os.Looper.loop(Looper.java:219) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8668) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by breautek** [comment] 2023-09-06 14:41
> java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference

This is signalling that you have a plugin entry but the class is missing. The generated `config.xml` that is used by the native platform is likely in a bad state.

Does removing and re-adding the platform reproduces the issue?

```
cordova platform remove android
cordova platform add android@12 --verbose
```

If that fixes the issue, then I'm guessing you had a plugin that didn't install properly for whatever reason.
If it doesn't fix your issue, then please post the results of the verbose output.

**Comment by breautek** [comment] 2023-09-06 17:25
The error clearly states that the issue is at your `window.html2pdf.create` line, where `html2pdf` is undefined.

There might be an error presumably inside `js/Html2pdf.js` preventing it to load properly, or perhaps it does not assign `window.html2pdf`.

This does not seem to be a bug with Cordova so I'm closing this issue.

**Closed by breautek** 2023-09-06 17:25 UTC
Labels: info-needed / awaiting response
