### ISSUE TITLE
Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 22 declared in library

### ISSUE THREAD

**Issue by prospong** [apache/cordova-android#1070] opened 2020-09-14 07:39 UTC
### Issue Type

- [x ] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
I encountered this bug when compiling the ionic project. I have followed the instructions on the Internet to continuously modify the project.properties under "myproject/platforms/android" and the project.properties under "myproject/platforms/android/Coedovalib".

But this did not take effect. When I cleared android and added android again, the same error still appeared. And, the value I changed was restored. 
## Information
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 22 declared in 
library [:CordovaLib] 

### Command or Code

<uses-sdk
   android:minSdkVersion="19"
   android:targetSdkVersion="29" />

### Version information
   Ionic:

   Ionic CLI                     : 6.11.8 
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.24
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 
   19 other plugins)

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (D:\Program Files\sdk)
   NodeJS            : v12.18.0 (D:\Program Files\nodejs\node.exe)
   npm               : 6.14.4
   OS                : Windows 10

## Checklist

- [x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment] 2020-09-15 16:35
This occurring because you (or a plugin) is setting the project min sdk to something lower than the cordova framework's min sdk, which for 9.x is set to 22.

Do you have the `android-minSdkVersion` preference set? If so I'd suggest to increase it to 22 or remove it to allow it to default to 22.

Do note that increasing the min sdk to 22 will limit your app to Android 5.1 or later.

**Comment by jcesarmobile** [comment] 2020-09-23 11:47
Yeah, Ionic apps used to include `<preference name="android-minSdkVersion" value="19" />` in the starters `config.xml`.

It's been removed, but for apps created before that, they should also manually remove that if using cordova-android 9+ as it uses `android-minSdkVersion` 22

**Comment by ebhsgit** [comment] 2020-10-18 03:32
@breautek 
I understand that cordova-android 9.x min sdk is 22. And the reason is due to effort involved to test vs sdk market share.

But I thought `android-minSdkVersion` is used to override that behaviour.

If I need to force minSdk lower than 22, how would I achieve this?

**Comment by dpogue** [comment] 2020-10-18 04:09
> But I thought `android-minSdkVersion` is used to override that behaviour.
> 
> If I need to force minSdk lower than 22, how would I achieve this?

You can use `android-minSdkVersion` to force a lower minSdk, but the code in cordova-android only supports SDK 22 and up. So if you are trying to target something lower, you'll probably also need to make changes to the Java code.

**Comment by ebhsgit** [comment] 2020-10-18 04:19
I understand that cordova-android 9.0 supports SDK 22 and up, and that the code is not tested against anything lower.

Currently, my issue is with the `android-minSdkVersion` options is that the build results in error
> Manifest merger failed...

Which is thrown by Cordova, not due to any errors from using deprecated Java/Android SDK API

How do we force the build to use a lower minSDK and ignore/bypass the error throw by Cordova?
And I understand that I will need to test and fix issues related to any unsupported SDK APIs.

**Comment by breautek** [comment] 2020-10-19 12:39
The problem is in the android project, we have 2 modules, the `app` module, and the `CordovaLib` module, and it looks like the preferences only changes the min sdk for the `app` module and the `CordovaLib` remains the default min sdk of 22, which is an incompatible app config.

As jcesar pointed out in the dev mailing list, I think this is something that can and should be fixed so I'll reopen this ticket.

To re-iterate from previous comments, this is only to keep the `CordovaLib` and `app` module min sdks in sync so it doesn't cause the gradle error. A PR that patches this is welcome.

This error could still come up via third-party libraries if they define a min sdk value. Lowering the min sdk could also make your app crash during runtime when attempting to use an API that may not exists on older devices.

In the meantime, this untested workaround could suffice:

__config.xml__
```xml
<widget ... xmlns:tools="http://schemas.android.com/tools">
    <edit-config file="AndroidManifest.xml" target="/manifest" mode="merge">
        <manifest xmlns:tools="http://schemas.android.com/tools" />
    </edit-config>
    <edit-config file="AndroidManifest.xml" target="/manifest/uses-sdk" mode="merge">
        <uses-sdk tools:overrideLibrary="<packageThatNeedsToBeOverridden>" />
    </edit-config>
</widget>
```

Where `packageThatNeedsToBeOverridden` should be a string of a package name. I don't quite remember exactly that this is for Cordova generally the error output for min sdk mismatches states the library package name. This can be a comma delimited list if there are multiple packages to override.

Lastly, I believe `<edit-config>` targeting `uses-sdk` can fail if your `AndroidManifest.xml` has no `<uses-sdk>` tag to modify. If that's the case of your app, I think you can replace it with `config-file` instead like so:

```xml
<config-file target="AndroidManifest.xml" parent="/manifest">
    <uses-sdk tools:overrideLibrary="<packageThatNeedsToBeOverridden>" />
<config-file>
```

**Comment by ebhsgit** [comment] 2020-10-23 05:33
For others that with similar needs

I was able to build by adding the following to my project's config.xml

```
        <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest">
            <manifest xmlns:tools="http://schemas.android.com/tools" />
        </edit-config>
        <config-file parent="/manifest" target="AndroidManifest.xml">
            <uses-sdk tools:overrideLibrary="org.apache.cordova" />
        </config-file>
```

As noted by @breautek 
```
    <edit-config file="AndroidManifest.xml" target="/manifest" mode="merge">
        <manifest xmlns:tools="http://schemas.android.com/tools" />
    </edit-config>
    <edit-config file="AndroidManifest.xml" target="/manifest/uses-sdk" mode="merge">
        <uses-sdk tools:overrideLibrary="<packageThatNeedsToBeOverridden>" />
    </edit-config>
```

Results in error
> Unable to graft xml at selector "/manifest/uses-sdk" from "[project path]\platforms\android\app\src\main\AndroidManifest.xml" during config install

**Closed** 2020-11-18 17:48 UTC

**Comment by aldhamdy** [comment] 2021-02-09 23:01
I solved the issue by declaring the Cordova android  version to 8

<engine name="android" spec="8.0.0" />

**Comment by DavidRiosProg** [comment] 2022-02-21 19:01
How do you access/find Cordova or config.xml?

**Comment by CodeProf14** [comment] 2022-04-04 02:32
Problem Fixed here : https://www.codeprofessionally.com/2022/04/manifest-merger-failed-uses-sdkminsdkversion-19-cannot-be-smaller-than-version-23-declared-in-library-vuforiaengine.html

**Comment by najeebkakar** [comment] 2024-12-15 08:26
android {
    defaultConfig {
        minSdk = 23
        ...
    }
    ...
}
