### ISSUE TITLE
Unable to handle valid url scheme as widget id with a leading number or contains a dash

### ISSUE THREAD

**Issue by mikkimichaelis** [apache/cordova-android#1330] opened 2021-08-29 17:40 UTC
# Bug Report

## Problem
widget id="com.1my-domain.app" version="1.9.37" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0"

### What is expected to happen?
Android platform to be added 

### What does actually happen?
Using cordova-fetch for cordova-android@^9.1.0
Adding android project...
Error validating package name. Must look like: `com.company.Name`. Currently is: `com.1my-domain.app`

## Information
removing both the '1' and '-' resolves the problem.   This url scheme works fine for iOS platform.  My understanding is that 'widget' should be any valid reverse domain.

### Command or Code
ionic cordova add platform android@9.1.0

### Environment, Platform, Device
macOS 11.2.3
9.0.0 (cordova-lib@9.0.1)
v12.22.1 (node)

### Version information
macOS 11.2.3
9.0.0 (cordova-lib@9.0.1)
v12.22.1 (node)
6.14.1 (ionic-cli)

## Checklist
- [ x] I searched for existing GitHub issues
- [ na] I updated all Cordova tooling to most recent version (not possible as latest android platform conflicts)
- [ x] I included all the necessary information above

**Comment by breautek** [comment] 2021-08-29 18:10
For the android platform, the bundle id becomes part of Java's package. By convention, Java uses reverse-domain style naming but not all domain characters are legal in java package names. Leading numbers is invalid in Java packages. I think hyphens are legal, but it cannot start with an hyphen. Note that every character after the dot is considered a "begin" of a new set.

You can read more on what is valid or not valid in java package names here: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html#:~:text=Naming%20Conventions,a%20programmer%20at%20example.com%20.

I'll be closing this issue as not a bug, but if you have any other questions, feel free to ask and I'll try to answer to the best of my ability.

**Closed by breautek** 2021-08-29 18:10 UTC

**Comment by mikkimichaelis** [comment] 2021-08-29 18:59
Thank you for the excellent quick response.  I've updated my package name appropriately.
