### ISSUE TITLE
Mixed translations for native date picker on Android

### ISSUE THREAD

**Issue by mciupka-dibit** [apache/cordova-android#1684] opened 2023-11-22 08:51 UTC
# Bug Report

### What is expected to happen?

The translation of the date picker should be completely in German.

### What does actually happen?

2 buttons of the date picker are translated into English. The rest is German.

![Samsung S23 App Debug](https://github.com/apache/cordova/assets/62941083/42229c7c-d130-44c9-85b8-7e4cb47a7507)

## Information

Create new cordova project: "cordova create example-project"
Add platform: "cordova platform add android@latest"
At the example www folder: index.html: Insert <input type="date">
cordova run android
Click on datepicker
The datepicker looks like the image above. 
The buttons marked with red circles are translated to english. 
Expected behaviour: Buttons have the same language (german) than the rest.

### Environment, Platform, Device

Devices with error: 
Samsung Galaxy S23 / Samsung Galaxy S22
Android 14
One UI 6.0

Devices with no error:
Samsung Galaxy XCover Pro
Android 13
One UI 5.1

Seems to ab an issue with Android 14. 
Tested with language German (Germany).
Please be aware that the emulator shows the correct translations. Only happens on real devices.
The devices have the standard configuration and there are no language addons etc. active.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by mciupka-dibit** [comment] 2023-11-22 14:23
Samsung Galaxy S23 Android System Webview: Version 119.0.6045.67 => Problem exists
Samsung Galaxy XCover Pro Android System Webview: 115.0.5790.166 => No Problem

Samsung Galaxy XCover Pro Android System Webview: *UPDATE* to 119.0.6045.163 => Problem exists

Issue seems not to be fixed

**Comment by breautek** [comment] 2023-11-22 14:35
Yes, it does seem to have been recently introduced by the webview, as you can observe going from 115 to 119 breaks the language. It would probably be best to report your findings at https://bugs.chromium.org/p/chromium/issues/list

> Please be aware that the emulator shows the correct translations. Only happens on real devices.

On this note, your current observations may also explain why it doesn't reproduce on the simulators. Android simulators ships with AOSP android, so they tend to have a really old version of the webview installed. If you install a Google Play enabled simulator with a Google Play enabled image, then the simulator will have Google Play and behave more closely to a retail device. You'll have the ability to login to a google account and update the webview to the latest version available. If you do this, I'd suspect you'll also observe the language issue on the simulator.

**Comment by mciupka-dibit** [comment] 2023-11-22 14:40
Thanks. I will report the issue there.

**Comment by jcesarmobile** [comment] 2023-11-26 15:18
closing since it's a bug in the WebView and it's already reported on the chromium repository, follow the linked issue for updates

**Closed by jcesarmobile** 2023-11-26 15:18 UTC
