### ISSUE TITLE
unwanted plugins added to project

### ISSUE THREAD

**Issue by Pepillo2019** [apache/cordova-android#677] opened 2019-02-19 00:57 UTC
Hi there!

With new cordova versions unwanted plugins are systematically added to the project while building android apps and cant find a way to get rid of them. Result is creating apps with unnecessary user permissions. I just created one app which does not need any permission at all but cordova forced a bunch of unwanted permissions cos it seems to inherit them from former app built that required all those permissions. Previous versions were easily controlled (added/removed) from AndroidManifest.xml file.

I tried some hooks, removed permissions from manifest.xml, android.json etc. but it did not work. The hook .js I created worked "silently/partially" as apparently it helps to remove permissions from the manifest.xml file but the unwanted permissions showed up again once the app was uploaded in google play console.

Any solution will be appreciated.

Cheers,

J

**Comment by janpio** [comment] 2019-02-19 09:52
What "new cordova versions" do you refer to?
What plugins are you talking about?

Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by Pepillo2019** [comment] 2019-02-19 16:22
I have installed android 6.3.0

Here is the list of plugins I believe are involved regarding this issue:
org.apache.cordova.geolocation
cordova-admobsdk		
cordova-plugin-geolocation
cordova-plugin-admob	

They are all automatically added to the project during the app building process. Installing/uninstalling them manually depending on the app to be built will make the process a night mare so there must be a solution like in previous versions as commented in my former email.

Thanks for your help!
Cheers,
J

**Comment by janpio** [comment] 2019-02-19 16:30
> I have installed android 6.3.0

Uh, that would be a very old version of Cordova Android, not a new one.

Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by Pepillo2019** [comment] 2019-02-19 16:50
You are right. That's not the newest version of cordova but new version for me as older versions I was using before (4.X.X) were working fine but i was forced to change it to comply with API policies from google play console (target API level 26 or higher). This is the most compatible version I found for the new apps I am building using cordova in order to comply with those policies

**Comment by rodrigograca31** [comment] 2019-03-15 22:16
@Pepillo2019 you are mixing things.

if you create a brand new cordova app:
```bash
cordova create hello com.example.hello HelloWorld
cd hello/
cordova platform add android
```
`cordova-android@7.1.4` will be used. and only one permission added:
`<uses-permission android:name="android.permission.INTERNET" />`

you can also try to force version 8: `cordova platform add android@^8.0.0`
also give 6.4.0 a try..... (I think I had similar issues before and 6.4.0 solved it)

but most importantly: those plugins are the ones adding permissions!
also: **STOP USING `cordova-plugin-admob` RIGHT NOW!**
**HE STEALS REVENUE FROM YOU AND HAS "REMOTE CONTROL" of your ads!**
(I have proof and he has disabled issues on GitHub to hide the problem....)

Please use:
`cordova plugin add cordova-plugin-admob-free --save` 
https://github.com/ratson/cordova-plugin-admob-free

Please close this issue as it seems not to be a cordova-android issue.

**Comment by Pepillo2019** [comment] 2019-03-16 00:08
copied!
I had some issues with admob-free while building the app that's why I ended up installing this admob plugin. I am wondering how this "parasitism" through plugins is possible and allowed. 
I will try your recommendations next time I build new app.
I will close this issue. Thanks a lot Rodrigo!

**Closed** 2019-03-16 00:08 UTC
Labels: support

**Comment by rodrigograca31** [comment] 2019-03-16 15:07
Glad I could help!
Had some free time and decided to try to help a bit and seems it paid off :)

**Comment by Pepillo2019** [comment] 2019-03-16 18:03
sure Rodrigo! muchas gracias ;-)

**Comment by SimoneMSR** [comment] 2019-04-15 09:16
I have the same issue with `cordova-plugin-filepath`

- cordova version `7.0.0`

ionic-cli prompts out that she 
`Discovered plugin "cordova-plugin-filepath" in config.xml. Adding it to the project`

but this is not truw. I have already deleted the `platform/android` folder several times.

**Comment by rodrigograca31** [comment] 2019-04-16 09:26
@SimoneMSR check your `config.xml` file.

also if you are on Linux or MacOS try: `grep -rn "cordova-plugin-filepath" .` and see which file/plugin requires that one.

**Comment by SimoneMSR** [comment] 2019-04-16 09:47
Thank you @rodrigograca31 , but i think the problem was elsewhere. I say 'was' because I have solved by doing
`rm package-lock.json`
Could it be the caouse?
