### ISSUE TITLE
Apps (including HelloCordova) don't display correctly

### ISSUE THREAD

**Issue by armandn** [apache/cordova-android#1478] opened 2022-08-23 18:24 UTC
# Bug Report

This is something that started happening only recently. I tested on two Samsung phones, an S20 Ultra and an A52, both running Android 12.

I created a test app with
```
cordova create test
cd test
cordova platform add android@11.0.0
cordova build android
```

Running the app on the phone and debugging it with Chrome Inspect Devices reveals the following: sometimes the app is smaller than the screen as seen below:

![test](https://user-images.githubusercontent.com/15320153/186230123-1a27646b-5689-4c46-9abb-8251c379739a.jpg)

In other cases (apparently randomly), the app does fill the screen, but it's actually scaled (it's more difficult to observe).

From Chrome Dev Tools we can see that the app size is different than the screen size:
```
screen.availWidth
412

screen.availHeight
915

document.body.offsetWidth
309

document.body.offsetHeight
629
```

Please note this is NOT simply an issue with the HTML `viewport` meta tag.

### What is expected to happen?

The application should use the whole available screen correctly.

### What does actually happen?

The application is sometimes smaller than the screen or, when it is the screen size, is actually zoomed.

### Environment, Platform, Device

Tested on two Samsung phones running Android 12.

### Version information

Cordova Android  10 & 11.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2022-09-23 01:44
Is this device specific?

I'm unable to reproduce this on an android 12 simulator. The simulator currently has webview version 91.0.4472.114.

I'd check if the webview is fully up to date (should be about version ~105.0) and if not, then try updating it.

**Comment by armandn** [comment] 2022-09-23 06:10
Just yesterday my Samsung received an update and now the problem is gone.
So I think it was a device bug, not webview-related (the webview was up to date).

**Comment by breautek** [comment] 2022-09-23 13:44
If that's the case I'll close this issue as it doesn't seem to be a cordova bug.

If the issue comes back, feel free to comment on it and we can re-open the issue.

**Closed by breautek** 2022-09-23 13:44 UTC
Labels: info-needed

**Comment by joefaron** [comment] 2022-09-27 19:16
Can confirm this happens with default code base on Samsung S20 FE.. good to know it's not cordova.  Wasted a day on this.. :\
![version](https://user-images.githubusercontent.com/702672/192615903-0549114c-524d-425b-a1b1-53cd37f08df7.jpg)
