### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by jringbox** [apache/cordova-android#936] opened 2020-03-31 16:34 UTC
# Bug Report

## Problem

Current project I have is retrieved from a code repository.  This has node_modules and all build related artifacts excluded.  After doing a `npm install` followed by `cordova -d build` android, the following is shown.

```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=C:\Users\jring\AppData\Local\Android\Sdk (recommended setting)
ANDROID_HOME=C:\Users\jring\AppData\Local\Android\Sdk (DEPRECATED)
Cannot read property 'toString' of null
TypeError: Cannot read property 'toString' of null
    at Object.module.exports.get_gradle_wrapper (C:\clinicallink\temp\git.latest\clinicallink-mobile\src-cordova\platforms\android\cordova\lib\check_reqs.js:96:27)
    at Object.module.exports.check_gradle (C:\clinicallink\temp\git.latest\clinicallink-mobile\src-cordova\platforms\android\cordova\lib\check_reqs.js:135:37)
    at ProjectBuilder.prepEnv (C:\clinicallink\temp\git.latest\clinicallink-mobile\src-cordova\platforms\android\cordova\lib\builders\ProjectBuilder.js:222:27)
    at Api.module.exports.run (C:\clinicallink\temp\git.latest\clinicallink-mobile\src-cordova\platforms\android\cordova\lib\build.js:174:20)
    at C:\clinicallink\temp\git.latest\clinicallink-mobile\src-cordova\platforms\android\cordova\Api.js:302:43
    at _fulfilled (C:\clinicallink\temp\git.latest\clinicallink-mobile\src-cordova\node_modules\q\q.js:854:54)
    at C:\clinicallink\temp\git.latest\clinicallink-mobile\src-cordova\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\clinicallink\temp\git.latest\clinicallink-mobile\src-cordova\node_modules\q\q.js:816:13)
    at C:\clinicallink\temp\git.latest\clinicallink-mobile\src-cordova\node_modules\q\q.js:624:44
    at runSingle (C:\clinicallink\temp\git.latest\clinicallink-mobile\src-cordova\node_modules\q\q.js:137:13)
```

The personal workspace for the project with node_modules and all build related directories under platforms/android which I keep separately builds fine.  I can't figure out what so different about my workspace artifacts and the clean checkout where node_modules and all build related artifacts are excluded.

Assistance is appreciated in resolving this issue.

### What is expected to happen?

successful build

### What does actually happen?

Cannot read property 'toString' of null

## Information

unable to provide complete steps for creating project to reproduce issue.

### Command or Code
This is built from CLI using "cordova build android".

### Environment, Platform, Device
Windows 10 Enterprise

### Version information
"cordova-android": "^8.1.0"
This project is under "src-cordova" using vue-cli-plugin-cordova 2.4.0.

## Checklist

- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by jringbox** [comment] 2020-03-31 16:47
I should also mention that line 92 of `check_reqs.js` produces null for result.stdout.  `__dirname` appears to be correct to where `getASPath.bat` is located.  Running the command locally does display the correct location to Android Studio.  I'm confused why this logic will not produce the string correctly for `result.stdout`.

**Comment by breautek** [comment] 2020-06-18 02:06
What's your cordova cli version? You can see this by running `cordova -v`

**Comment by PallaviK91** [comment] 2020-07-01 09:00
I am facing the same issue on windows. Were you able to figure out the issue?

**Comment by jringbox** [comment] 2020-07-05 02:28
@breautek I apologize for the very late response.  I'm using 8.1.0.

@PallaviK91 I still have to perform the step I mentioned above to build.  The copy trick I mentioned is still the only quick way around the problem.

**Comment by breautek** [comment] 2020-07-05 02:38
First I'd try using cli version 9 and see if you can still reproduce the problem. Cordova-android@9 has also been released since you've first open this issue and it has changed quite a bit in this area, so it might be worth upgrading to `cordova-android@9` as well.

> Why would npm install cause result.stdout in the js script to cause a wrong lookup of android studio path? Or there something else going on that I'm missing?

If you're able to log out information, I'd check both the exit code and make `stderr`. Perhaps something about the script is erroring for some reason.

**Comment by PallaviK91** [comment] 2020-07-06 04:40
Thanks for your reply. Issue is fixed by doing nothing. In my case, with fresh checkout of project issue is resolved. Not sure what went wrong with local copy.

**Comment by breautek** [comment] 2020-07-20 22:24
> Thanks for your reply. Issue is fixed by doing nothing. In my case, with fresh checkout of project issue is resolved. Not sure what went wrong with local copy.

It could be a race condition.

I installed my dev environment on a windows machine to try to reproduce some of these "windows" issues that have been reported, but I haven't reproduced this with a simple hello world app. Is it possible that you can share all your plugins, or perhaps provide a [sample reproduction](https://github.com/apache/cordova-contribute/blob/master/deprecation.md) app?

**Comment by jringbox** [comment] 2020-08-13 16:04
I'll have to see.  The last time I tried to create a sample app, I couldn't reproduce it.  Right now I've added more libraries to the application under the cordova context and I was able to get the problem again.  \*sigh\*

I went and created a new plain app but I added all the plugin and libraries to cordova and couldn't reproduce the problem.  Maybe I also need to add the packages to the vueJs also?  Don't know.

As I mentioned, on a fresh check out from git (Azure git repository), making a copy of the platforms directory, deleting the old, and renaming the copy to platforms, fixes the issue.  I find this very strange and doing this fixes the problem every time on the fresh checkout.  If it was a race condition, then these steps I do shouldn't fix the problem everytime.

**Comment by breautek** [comment] 2020-08-13 16:09
> I'll have to see. The last time I tried to create a sample app, I couldn't reproduce it. Right now I've added more libraries to the application under the cordova context and I was able to get the problem again. *sigh*
> 
> I went and created a new plain app but I added all the plugin and libraries to cordova and couldn't reproduce the problem. Maybe I also need to add the packages to the vueJs also? Don't know.
> 
> As I mentioned, on a fresh check out from git (Azure git repository), making a copy of the platforms directory, deleting the old, and renaming the copy to platforms, fixes the issue. I find this very strange and doing this fixes the problem every time on the fresh checkout. If it was a race condition, then these steps I do shouldn't fix the problem everytime.

Try using Node >= 10.10.0. This issue could be related to https://github.com/apache/cordova-android/issues/913#issuecomment-670453282

**Comment by breautek** [comment] 2022-05-18 03:20
Closing as stale.

> I find this very strange and doing this fixes the problem every time on the fresh checkout.

It could have been an issue in a sub-dependency so on a fresh checkout, you would have had all sub-dependencies updated to their latest patches.

**Closed by breautek** 2022-05-18 03:20 UTC
Labels: info-needed
