### ISSUE TITLE
Gradle fails to sync after creating app

### ISSUE THREAD

**Issue by florianmonfort** [apache/cordova-android#881] opened 2019-12-12 04:47 UTC
# Bug Report

## Problem

After creating the app using ionic cordova prepare android, and opening the Project in AS, the Sync fails immediately.

### What is expected to happen?

App should sync normally.

### What does actually happen?

Android Studio provides the following error during sync:

`ERROR: startup failed:
build file '/Users/dev/Developer/diningcity-assistant/platforms/android/app/build.gradle': 297: expecting anything but ''\n''; got it anyway @ line 297, column 24.
       implementation27.+"
                          ^

1 error

Open File`

## Information

Here is the result of cordova prepare android:

`> cordova prepare android
Discovered saved plugin "mx.ferreyra.callnumber". Adding it to the project
Plugin "call-number" already installed on android.
Plugin "call-number" already installed on ios.
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
config file *-Info.plist requested for changes not found at /Users/dev/Developer/diningcity-assistant/platforms/android/*-Info.plist, ignoring
cordova-android-support-gradle-release: Android platform: V7+
cordova-android-support-gradle-release: Wrote custom version '27.+' to /Users/dev/Developer/diningcity-assistant/platforms/android/app/build.gradle
cordova-android-support-gradle-release: Wrote custom version '27.+' to /Users/dev/Developer/diningcity-assistant/platforms/android/cordova-android-support-gradle-release/dcapp-cordova-android-support-gradle-release.gradle
➜  diningcity-assistant git:(master) ✗`

### Command or Code

ionic cordova prepare android

or

cordova prepare android

### Environment, Platform, Device

MacOS

### Version information

ionic info

Ionic:

   Ionic CLI                     : 5.4.12 (/Users/dev/.nvm/versions/node/v12.1.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0-dev.201904251558.2457a23
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.3
   @angular/cli                  : 7.2.3
   @ionic/angular-toolkit        : 1.2.3

Capacitor:

   Capacitor CLI   : 1.0.0-beta.22
   @capacitor/core : 1.0.0-beta.19

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.4.1, (and 16 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.1
   NodeJS     : v12.1.0 (/Users/dev/.nvm/versions/node/v12.1.0/bin/node)
   npm        : 6.9.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.2.1 Build version 11B500

`gradle -v

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_211 (Oracle Corporation 25.211-b12)
OS:           Mac OS X 10.15.1 x86_64`

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2020-04-13 00:34
This is very likely caused by a plugin.

Given the error:
```
build file '/Users/dev/Developer/diningcity-assistant/platforms/android/app/build.gradle': 297: expecting anything but ''\n''; got it anyway @ line 297, column 24.
implementation27.+"
```

And this output:
`Android platform: V7+ cordova-android-support-gradle-release: Wrote custom version '27.+' to /Users/dev/Developer/diningcity-assistant/platforms/android/app/build.gradle`

I would question the `cordova-android-support-gradle-release` plugin...

**Comment by erisu** [comment] 2021-07-29 09:14
I am closing out this ticket.
* Was unable to reproduce the issue.
* Cordova-Android's codebase does not have written `27.+` anywhere.
* The information provided also appears to be pointing to a plugin issue (`cordova-android-support-gradle-release`). It appears the plugin is modifying the Gradle file incorrectly and causing the file to become malformed.

The `cordova-android-support-gradle-release` plugin appears to be deprecated and unmaintained. If you're still using this plugin you should try and reach out to the developer to see.

Also, seeing how the old platform version was, you might want to try and upgrade the project. You might not need the plugin anymore.

**Closed by erisu** 2021-07-29 09:14 UTC
