### ISSUE TITLE
[8.0.0] Android environment variables output

### ISSUE THREAD

**Issue by janpio** [apache/cordova-android#671] opened 2019-02-14 15:05 UTC
See the folllowing output:

```
E:\Projects\throwaway\cordovaAndroid8Test  (helloworld@1.0.0)
λ cordova run android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\Jan\AppData\Local\Android\sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE
> Task :app:preDebugBuild
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :CordovaLib:compileDebugRenderscript UP-TO-DATE
> Task :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> Task :CordovaLib:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:generateDebugResources UP-TO-DATE
> Task :CordovaLib:packageDebugResources UP-TO-DATE
> Task :CordovaLib:generateDebugRFile UP-TO-DATE
> Task :CordovaLib:prepareLintJar UP-TO-DATE
> Task :CordovaLib:generateDebugSources UP-TO-DATE
> Task :CordovaLib:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
> Task :app:javaPreCompileDebug
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest
> Task :app:processDebugResources

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :app:compileDebugJavaWithJavac

> Task :app:compileDebugNdk NO-SOURCE
> Task :app:compileDebugSources
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:mergeDebugShaders UP-TO-DATE
> Task :CordovaLib:compileDebugShaders UP-TO-DATE
> Task :CordovaLib:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForDebug
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug
> Task :app:transformDexArchiveWithDexMergerForDebug
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:compileDebugNdk NO-SOURCE
> Task :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug
> Task :app:packageDebug
> Task :app:assembleDebug
> Task :app:cdvBuildDebug

BUILD SUCCESSFUL in 13s
42 actionable tasks: 12 executed, 30 up-to-date
Built the following apk(s):
        E:\Projects\throwaway\cordovaAndroid8Test\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\Jan\AppData\Local\Android\sdk (DEPRECATED)
No target specified and no devices found, deploying to emulator
No emulator images (avds) found.
1. Download desired System Image by running: "C:\Users\Jan\AppData\Local\Android\sdk\tools\android.bat" sdk
2. Create an AVD by running: "C:\Users\Jan\AppData\Local\Android\sdk\tools\android.bat" avd
HINT: For a faster emulator, use an Intel System Image and install the HAXM device driver
```

It contains this bit twice:
```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\Jan\AppData\Local\Android\sdk (DEPRECATED)
```
although this is not really relevant to me _at all_ as everything is fine with my environment variables. Maybe we should only show this if there is a problem, and otherwise just focus on the important output?

**Comment by pranav9k** [comment] 2019-05-02 03:10
I got the same issue. Any solution?

**Comment by janpio** [comment] 2019-05-02 08:25
This is not an problem, but a tiny cosmetic thing to fix. 
If you have a problem, please create a new issue and describe your problem with output and code.

**Comment by hiepxanh** [comment] 2019-05-13 08:08
I have the same problem, dont know to fix
```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\hiepx\AppData\Local\Android\Sdk (DEPRECATED)
Reading build config file: E:\project\test-mobile\build.json
Reading the keystore from: E:\project\test-mobile\debug.keystore
```

**Comment by pranav9k** [comment] 2019-05-13 08:15
Set the system environment variable ANDROID_SDK_ROOT, the value would be the Android SDK path(exactly the same as for the variable ANDROID_HOME).

**Comment by janpio** [comment] 2019-05-13 11:01
Again, you don't have "the same problem" @hiepxanh as this refers to duplicated ouput, which is cumbersome but not a problem. If something is actually broken for you, please create a new issue.

**Comment by light8822** [comment] 2019-05-31 21:44
Hello anyone does know's how to fix it?

**Comment by hiepxanh** [comment] 2019-06-01 02:37
@light8822  I fixed it by remove android studio, install it again, turn on `hyper V` and `window hypervisor plaform` and restart computer.
worked on ryzen 1600 AMD 
[https://android-developers.googleblog.com/2018/07/android-emulator-amd-processor-hyper-v.html](https://android-developers.googleblog.com/2018/07/android-emulator-amd-processor-hyper-v.html)

**Comment by owen800q** [comment] 2019-07-29 08:17
How to fix this ?

**Comment by breautek** [comment] 2019-07-29 13:49
> How to fix this ?

As stated several times, this issue is related to build information being printed out multiple times. It is a cosmetic issue only and doesn't affect the actual working of the project. If something is actually broken for you, please create a new issue and describe your problem with build output and/or related code.

Thanks.

**Comment by goffioul** [comment] 2020-02-03 14:43
Shouldn't `cordova.gradle` also be adapted:
https://github.com/apache/cordova-android/blob/master/framework/cordova.gradle#L84

**Comment by breautek** [comment] 2020-04-13 05:43
This is caused by code in the `cordova-lib`.

It's run method calls on the `Api.build` at https://github.com/apache/cordova-lib/blob/master/src/cordova/run.js#L46

Then it also calls on `Api.run` at https://github.com/apache/cordova-lib/blob/f7f9343ca9b3c616570b5d2d0a00f2e39e0b1424/src/cordova/run.js#L53

Both `Api` methods calls on `check_reqs`, which is why we see the duplicated output.

**Comment by breautek** [comment] 2020-08-11 00:51
Closing this as `cordova-android@9` now produces an output that looks like:

```
cordova run android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/development/Android/Sdk (recommended setting)
ANDROID_HOME=/development/Android/Sdk (DEPRECATED)
Using Android SDK: /development/Android/Sdk
Subproject Path: CordovaLib
Subproject Path: app

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
```

No more duplicates.

**Closed by breautek** 2020-08-11 00:51 UTC
Labels: version: 8.0.0
