### ISSUE TITLE
Javascript functionalities for my cordova app doesn't work on android 4.4.2 but works on higher versions

### ISSUE THREAD

**Issue by adekunle11** [apache/cordova-android#886] opened 2019-12-18 14:39 UTC
Javascript functions like button clicks, and onesignal plugin code for usage do not work on my android 4.4.2, I've tested on android 5.0 and 8.0, it works fine
My cordova version is 9.0
My minSdkVersion is set to 19 which is 4.4.2 right?
Please what can I do

**Comment by breautek** [comment] 2019-12-18 14:52
android sdk 19 is android 4.4.x, so yes it includes 4.4.2.

The major difference between 4.4 and android 5.0 or 8.0 is that the webview on 4.4 is stuck at an really old version of chrome. (I believe it's chrome 30 if memory serves me right). So there are a lot of JS features that are not supported back then.

The modern chrome debugger doesn't work very well on older devices, but you should still be able to use it to remote debug your app and at least view the javascript console for errors.

**Comment by adekunle11** [comment] 2019-12-18 15:18
@breautek This is what it shows
![20191218_161542](https://user-images.githubusercontent.com/45455861/71098415-f74a6f80-21b1-11ea-87a8-87a5613fc818.jpg)

**Comment by breautek** [comment] 2019-12-18 15:21
`OneSignal` has a syntax error which I would guess is the root cause of all the other errors.

**Comment by dpogue** [comment] 2019-12-18 15:21
This is a bug in the onesignal plugin, not in Cordova Android.

It looks like it was fixed in onesignal-cordova-plugin [v2.5.2](https://github.com/OneSignal/OneSignal-Cordova-SDK/releases/tag/2.5.2), and the latest version is v2.8.1.

**Closed by dpogue** 2019-12-18 15:21 UTC
Labels: support
