### ISSUE TITLE
Application stuck on splash screen

### ISSUE THREAD

**Issue by araafat3** [apache/cordova-android#1044] opened 2020-08-10 15:06 UTC
# Bug Report

### What is expected to happen?
go to screen after splash screen

### What does actually happen?
Stuck in splash screen

## Information

run app on tecno C8 then app stuck on splash screen
This problem is coming randomly not all the timee

### Command or Code
Stacktrace:

08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.342 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors
08-10 14:36:23.343 9169-9220/com.uba.vericash W/chromium: [WARNING:file_descriptor_set_posix.cc(22)] FileDescriptorSet destroyed with unconsumed descriptors

### Environment, Platform, Device

Android

### Version information
Mobile: tecno C8
Android Version: 5.0.2
Cordova Version:8.0.0
Android platform version:8.1.0
Node version:10.16.3

**Comment by breautek** [comment] 2020-08-10 16:19
Thank you for your report.

We generally don't support old releases.

The latest `cordova-android` release is `9.0.0` minimum supported android version is android 5.1.

It does not support `Android 5.0`, for two main reasons:
- because market share data shows owners of 5.0 devices are insignificant
- because not all vendors supported the upgradable webview that android 5.0 suppose to introduce, and many devices were stuck on a buggy version of chrome. These issues were resolved in android 5.1. 

I'm not sure if this describes your specific android device.

Based on the stacktrace, this is a problem with chrome webview itself. If your device is able to reproduce this issue on the latest webview release (I believe it's chrome 84 at the time of writing...), then I would consider raising an issue with the chromium team.

**Just** in case the provided stacktrace is not actually related to your issue. A stuck splashscreen is often a symptom of a javascript error that is occurring on launch. Connecting to the remote web inspector using [chrome://inspect](chrome://inspect) may also point you to the right direction for a solution.

I'll be closing this because we use github for tracking feature requests and bugs only. If this is a cordova bug, it likely won't be fixed since it appears to be targeting an old version of Cordova. If you require further support, I welcome you to join our [slack](http://slack.cordova.io/) channel.

**Closed by breautek** 2020-08-10 16:19 UTC

**Comment by araafat3** [comment] 2020-08-11 02:05
@breautek 
many thanks for info and quick replay
this is a problem Based on the stacktrace but at android 5.0.2 was not using chrome but used web browser android
thank you for raising it chromium team
