### ISSUE TITLE
AAPT: error: <adaptive-icon> elements require a sdk version of at least 26.

### ISSUE THREAD

**Issue by gouteru** [apache/cordova-android#1523] opened 2022-12-03 14:25 UTC
I have upgraded Cordova android 10 to 11 and get an error when I did "cordova build android". 

```
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     ERROR:/Users/gouteru/dev/vue/myapp/platforms/android/app/src/main/res/drawable/ic_cdv_splashscreen.xml: 
       AAPT: error: <adaptive-icon> elements require a sdk version of at least 26.
```

I have setup adaptive icon, legacy icon and notification icon with Image Asset Studio of Android Studio 2021.03 Dolphin Patch1.

This error is gone when I changed minSdkVersion from 22 to 26 in config.xml. 
But I don't want to change minSdkVersion because some of my app users using Android7.1 or older OS versions.
Please teach me how to solve this error without changing minSdkVersion.

Here's my config.xml regarding android.

```
    <platform name="android">
        <preference name="android-compileSdkVersion" value="32" />
        <preference name="AndroidXEnabled" value="true" />
        <preference name="GradlePluginKotlinEnabled" value="true" />
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" />
        </edit-config>
        <resource-file src="res/android/drawable/ic_launcher_background.xml" target="app/src/main/res/drawable/ic_launcher_background.xml" />
        <resource-file src="res/android/drawable/ic_launcher_foreground.xml" target="app/src/main/res/drawable/ic_launcher_foreground.xml" />
        <resource-file src="res/android/mipmap-anydpi-v26/ic_launcher.xml" target="app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml" />
        <resource-file src="res/android/mipmap-anydpi-v26/ic_launcher_round.xml" target="app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml" />
        <resource-file src="res/android/mipmap-hdpi/ic_launcher.png" target="app/src/main/res/mipmap-hdpi/ic_launcher.png" />
        <resource-file src="res/android/mipmap-hdpi/ic_launcher_round.png" target="app/src/main/res/mipmap-hdpi/ic_launcher_round.png" />
        <resource-file src="res/android/mipmap-mdpi/ic_launcher.png" target="app/src/main/res/mipmap-mdpi/ic_launcher.png" />
        <resource-file src="res/android/mipmap-mdpi/ic_launcher_round.png" target="app/src/main/res/mipmap-mdpi/ic_launcher_round.png" />
        <resource-file src="res/android/mipmap-xhdpi/ic_launcher.png" target="app/src/main/res/mipmap-xhdpi/ic_launcher.png" />
        <resource-file src="res/android/mipmap-xhdpi/ic_launcher_round.png" target="app/src/main/res/mipmap-xhdpi/ic_launcher_round.png" />
        <resource-file src="res/android/mipmap-xxhdpi/ic_launcher.png" target="app/src/main/res/mipmap-xxhdpi/ic_launcher.png" />
        <resource-file src="res/android/mipmap-xxhdpi/ic_launcher_round.png" target="app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png" />
        <resource-file src="res/android/mipmap-xxxhdpi/ic_launcher.png" target="app/src/main/res/mipmap-xxxhdpi/ic_launcher.png" />
        <resource-file src="res/android/mipmap-xxxhdpi/ic_launcher_round.png" target="app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png" />
        <!-- <icon density="ldpi" src="res/icon/android/mipmap-ldpi/ic_launcher.png" />
        <icon density="mdpi" src="res/icon/android/mipmap-mdpi/ic_launcher.png" />
        <icon density="hdpi" src="res/icon/android/mipmap-hdpi/ic_launcher.png" />
        <icon density="xhdpi" src="res/icon/android/mipmap-xhdpi/ic_launcher.png" />
        <icon density="xxhdpi" src="res/icon/android/mipmap-xxhdpi/ic_launcher.png" />
        <icon density="xxxhdpi" src="res/icon/android/mipmap-xxxhdpi/ic_launcher.png" /> -->
        <!-- <splash density="land-hdpi" src="res/screen/android/splash-land-hdpi.png" />
        <splash density="land-ldpi" src="res/screen/android/splash-land-ldpi.png" />
        <splash density="land-mdpi" src="res/screen/android/splash-land-mdpi.png" />
        <splash density="land-xhdpi" src="res/screen/android/splash-land-xhdpi.png" />
        <splash density="land-xxhdpi" src="res/screen/android/splash-land-xxhdpi.png" />
        <splash density="port-hdpi" src="res/screen/android/splash-port-hdpi.png" />
        <splash density="port-ldpi" src="res/screen/android/splash-port-ldpi.png" />
        <splash density="port-mdpi" src="res/screen/android/splash-port-mdpi.png" />
        <splash density="port-xhdpi" src="res/screen/android/splash-port-xhdpi.png" />
        <splash density="port-xxhdpi" src="res/screen/android/splash-port-xxhdpi.png" /> -->
        <preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/android/mipmap-anydpi-v26/ic_launcher_round.xml" />
        <preference name="android-minSdkVersion" value="22" />
        <preference name="android-targetSdkVersion" value="32" />
        <allow-intent href="market:*" />
        <preference name="AndroidLaunchMode" value="singleTask" />
        <preference name="AndroidInsecureFileModeEnabled" value="true" />
        <preference name="AndroidPersistentFileLocation" value="Compatibility" />
        <preference name="AutoHideSplashScreen" value="true" />
        <!-- <preference name="SplashScreenDelay" value="0" /> -->
        <preference name="SplashScreenDelay" value="3000" />
        <feature name="Calendar">
            <param name="android-package" value="nl.xservices.plugins.Calendar" />
        </feature>
        <!-- <preference name="GradlePluginGoogleServicesEnabled" value="true" />
        <preference name="GradlePluginGoogleServicesVersion" value="4.2.0" /> -->
    </platform>
```

**Comment by breautek** [comment] 2022-12-03 14:42
Use a rasterized image, like a png for `AndroidWindowSplashScreenAnimatedIcon` instead of a vector.

Naturally, without vectors you wouldn't be able to use an animation, despite the preference name, but using rastered images has broad support over older devices.

I understand the Cordova docs currently shows using vectors but PNGs as well as a couple of other rasterized formats are supported by Android. The docs can be definitely improved on this subject. Using vector formats requires API 26.

Closing as not a bug, but if you have further questions don't hesitate to ask.

**Closed by breautek** 2022-12-03 14:42 UTC

**Comment by breautek** [comment] 2022-12-03 15:26
Just making a slight correction, an XML vector can be used on older devices, however not all vector features are supported.

If you're trying to use an adaptive-icon (which appears to be the case here), that requires API 26.

Additionally, XML drawables that uses the following directives requires API 24:
- fillColor
- fillType
- strokeColor

XML drawables that doesn't use the above directives should be supported on API 21 and later, which is the Cordova default minimum SDK.

Created docs pr at https://github.com/apache/cordova-docs/pull/1276 to hopefully make this more clear.

**Comment by gouteru** [comment] 2022-12-04 06:20
Thank you very much.
I changed xml file to png, build succeeded without the error.
`<preference name="AndroidWindowSplashScreenAnimatedIcon" value="res/android/mipmap-hdpi/ic_launcher_round.png" />`

However the resolution is not match with my pixel 5a. How can I specify png files with multi density?

**Comment by gouteru** [comment] 2022-12-04 07:23
I have found out the resolution for the png icon. 200x80dp is needed.
[https://developer.android.com/guide/topics/ui/splash-screen#splash_screen_dimensions](https://developer.android.com/guide/topics/ui/splash-screen#splash_screen_dimensions)

**Comment by breautek** [comment] 2022-12-04 14:46
> I have found out the resolution for the png icon. 200x80dp is needed. https://developer.android.com/guide/topics/ui/splash-screen#splash_screen_dimensions

Yup, so you'll scale that to the largest dpi you intend to support. I forget the individual scales but if xxxhdpi is 4x, then you multiply the resolution by 4 to get your pixel resolution that the image should be at. DP base scale is mdpi, so mdpi scale is effectively x1. If you don't scale the DP value, you'll get a fuzzy/blurry image on larger resolution devices.

For reference, the icon we've been using at my work is a 2667x2667 PNG

![xxxhdpi](https://user-images.githubusercontent.com/11200662/205497018-5e035f18-97e8-4741-a3d7-be604fefc744.png)

Not the entire space is usable, about 30% around the edges are consumed by a mask and won't be visible in the end-product. The actual icon itself consumes most of the usable screen space, which you could visualise by drawing a circle around the bounds of the icon. Different devices appear to scale down as appropriate, so even if they are using a larger resolution than intended, it still appears to work.

It will be more efficient to utilise actual vectors (but not an adaptive icon), but you'll likely need to require minimum API 24 to use a vector image.
