### ISSUE TITLE
Project stopped to build with error appComponentFactory

### ISSUE THREAD

**Issue by greggy** [apache/cordova-android#755] opened 2019-06-27 12:41 UTC
# Bug Report
We build our project too long time without any changes, but a week ago we got an error:

platforms/android/build/intermediates/manifests/full/armv7/debug/AndroidManifest.xml:82: error: No resource identifier found for attribute 'appComponentFactory' in package 'android'

## Problem
We cannot build our project, the only way is to change `target` from `android-26` to `android-28` manually in `platforms/android/project.properties`.

### What is expected to happen?
We can build it automaticlly.

### What does actually happen?
We cannot do it.

### Environment, Platform, Device

Debian stretch

### Version information

gradle 4.4.1
cordova 8.1.2
cordova-android 6.3.0
npm 6.7.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2019-06-27 12:50
This problem occurs if you're using out-dated build tools, which `cordova-android@6` uses. Upgrading to `cordova-android@^8` should solve this issue.

**Comment by 2garryn** [comment] 2019-06-27 13:09
> This problem occurs if you're using out-dated build tools, which `cordova-android@6` uses. Upgrading to `cordova-android@^8` should solve this issue.

Thanks a lot for answer. I got the same issue. But one thing is not clear for me. What is reason of this issue?
How build tools become automatically out-dated? We use fixed versions of dependencies  everywhere. 
One time cordova just stopped to build, and we didn't update anything.

**Comment by breautek** [comment] 2019-06-27 13:13
Not exactly an expert, but I think its part of the google tool set. Not 100% sure though. I've ran a similar problem in my projects.

**Comment by greggy** [comment] 2019-06-27 14:17
The problem that we cannot easily update cordova-android because we have old dependencies we cannot remove. The only chance to get why this error occurred.

**Comment by breautek** [comment] 2019-06-27 14:42
I believe the issue is related to Google's update here https://developers.google.com/android/guides/releases#june_17_2019

If there is any dependency, including plugin dependencies that depend on any version greater than listed here, you'll need to use Android SDK 28+

In my experience many library authors don't pin their dependencies properly so my best educated guess is you have a plugin that is depending on the latest version of a library that now requires Android SDK >= 28 and gradle >= 3.2.1. `cordova-android` 6.3.0 doesn't meet these dependencies. I had a look at 6.3.0 branch on `cordova-android` and it appears all dependencies are pinned to an exact version, so that only leaves plugins.

The easiest way to prove this I think is to create a minimal app without plugins and build. Then add each plugin one at a time and rebuild until the issue appears.

**Comment by breautek** [comment] 2020-04-13 14:48
Closing, solutions are posted above.

**Closed by breautek** 2020-04-13 14:48 UTC
Labels: support
