### ISSUE TITLE
Help, the drawable picture in my release apk package is always renamed, that picture I do not want it to be renamed, what should I do

### ISSUE THREAD

**Issue by ChinaGc** [apache/cordova-android#1655] opened 2023-08-29 10:10 UTC
# Bug Report

### What is expected to happen?
Image resources do not want to be renamed

### What does actually happen?

has renamed

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by ChinaGc** [comment] 2023-08-29 10:21
like this 
![DF2C3315-17D7-4812-A650-CDCD2D6A507E](https://github.com/apache/cordova-android/assets/18680644/8b464bb5-dd34-4965-87da-7fa4f5933620)

**Comment by breautek** [comment] 2023-08-30 19:21
Are you using any obsfucation plugins like proguard?

If so, it would do stuff like this

**Comment by ChinaGc** [comment] 2023-08-31 08:56
> Are you using any obsfucation plugins like proguard?
> 
> If so, it would do stuff like this
Thank you for your reply, this is a newly created project, without any configuration, and without adding any plugins.
![微信截图_20230831133128](https://github.com/apache/cordova-android/assets/18680644/0d938b70-68e9-412e-a62d-3b1feee95983)

**Comment by ChinaGc** [comment] 2023-08-31 08:58
> Are you using any obsfucation plugins like proguard?
> 
> If so, it would do stuff like this

Hi，Thank you for your reply, this is a newly created project, without any configuration, and without adding any plugins.
![微信截图_20230831133128](https://github.com/apache/cordova-android/assets/18680644/06b4ad04-9647-4dea-83fb-1f47b982f31b)

**Comment by faugusztin** [comment] 2023-08-31 23:10
This is caused by Android Gradle Plugin 4.2 defaulting to android.enableResourceOptimizations=true (which will be the only option in future) - [source](https://stackoverflow.com/a/68464092).

On other side, you are supposed to read these files using corresponding resource identifier in Android code using corresponding [API call](https://developer.android.com/reference/android/content/res/Resources.html#getIdentifier(java.lang.String,%20java.lang.String,%20java.lang.String)).

**Comment by breautek** [comment] 2023-08-31 23:59
@faugusztin 

Good find.

Starting in Gradle 8 it will be forcefully enabled as shown in their [source](https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/options/BooleanOption.kt#190).

Gradle 8 will be used in our next major so I don't see any point in adding any kind of feature to change this.

> Alternatively files you want to read in a Cordova application outside a Cordova plugin should be inside the assets folder or ideally within Cordova www folder, which gets copied to assets/www in final APK file.

Also true

Closing as won't fix.

**Closed by breautek** 2023-08-31 23:59 UTC
Labels: info-needed / awaiting response
