### ISSUE TITLE
ANR rate at 4%, Slow cold start at 100% because of the splash screen

### ISSUE THREAD

**Issue by KekGames** [apache/cordova-android#1510] opened 2022-10-17 11:27 UTC
# Bug Report

## Problem
I'm using Construct 3 engine. After a certain [update ](https://www.construct.net/en/make-games/releases/beta/r303)in which they moved to a newer Cordova version, the ANR rate and Slow cold starts went up significantly, with the most frequent ANR report being "Native method - android.os.MessageQueue.nativePollOnce". After some investigation I tried disabling the new splash screen by commenting out `cordovaInterface.pluginManager.postMessage("setupSplashScreen", splashScreen);` in CordovaActivity.java.
After this the ANRs and Slow cold starts went back to normal, but you get a few seconds of black screen instead of the splash which is not ideal.
![Untitled-2](https://user-images.githubusercontent.com/42392288/196163058-279030bc-7016-4df0-99cb-b606ddedcc7c.png)
### What is expected to happen?
Low ANR and Slow cold start rates

### What does actually happen?
High ANR and Slow cold start rates

## Information

This also affects other Construct 3 users, so I filed an issue with C3 team https://github.com/Scirra/Construct-3-bugs/issues/6166
But they suggested reporting it here instead.

### Command or Code

`cordovaInterface.pluginManager.postMessage("setupSplashScreen", splashScreen);`

### Environment, Platform, Device

Construct 3, Android, Different devices

### Version information

I'm not sure which versions Construct 3's build service is using

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by AshleyScirra** [comment] 2022-10-17 12:20
Some more context: originally Construct used cordova-android@10.1.2, and a couple of months ago we updated to cordova-android@11.0.0. From regression testing users have established that it was the update to cordova-android@11.0.0 which started to cause high ANR and cold start times. Removing the `"setupSplashScreen"` message appears to work around the problem, but completely removes the splash screen. This all seems to indicate that the new splash screen implementation in cordova-android@11.0.0 is causing slow cold start rates and high ANRs.

**Comment by breautek** [comment] 2022-10-17 18:20
`cordovaInterface.pluginManager.postMessage("setupSplashScreen", splashScreen);`

This line itself just broadcasts a message to cordova plugins. I think it's probably safe to assume there are no plugins except for Cordova's (internal) splashscreen plugin which responds to `"setupSplashScreen"` by actually configuring the Splashscreen. It however does have to iterate over all plugins which has to be a synchronized process since Java hashmaps are not threadsafe. If an app has several plugins I can see how this could be slow. The best way to test if this is the case is to probably eliminate this step altogether. I think you're probably in a better position to experiment, but here is what I'd try:

Replace/comment out:
```java
// Setup the splash screen based on preference settingscordovaInterface.pluginManager.postMessage("setupSplashScreen", splashScreen);
```

with...

```java
cordovaInterface.pluginManager.getPlugin(SplashScreenPlugin.PLUGIN_NAME).onMessage("setupSplashScreen", splashscreen);
```

Untested, and not intended to be production code, but it should skip the synchronized hashmap iteration and go straight to the splashscreen setup code, at the expense that other plugins won't receive the message (Which imo, probably not an issue). If you still see slow starts, then it suggests it might be the Android Splashscreen API itself that is causing the slow start.

It's also not clear what a slow start here means. Is this counting time before seeing the splashscreen, or does it include time spent showing the splashscreen? If the latter, using `SplashScreenDelay` to artificially keep the splashscreen displayed for an extended period of time could trigger slow starts I presume? I don't know if that is something you are using or not, it's just a thought.

**Comment by KekGames** [comment] 2022-10-19 09:52
@breautek thanks for suggestion. I tried this but it doesn't change anything. 
The time when the splash appears on the screen definitely counts towards "slow start". So maybe Google also falsely registers "app not responding" while the game is actually loading.

**Comment by erisu** [comment] 2022-10-19 10:42
@KekGames 

I am just thinking aloud here but based on your last comment and my understanding of the ANR, it is possible that the loading of the game is blocking and causing the ANR to increase.

> While the game is actually loading.

Generally, I read that App Not Responding (ANR) starts to arise when an Activity has not finished an operation within 5 seconds.

Are you using the Splash Screen configurations `AutoHideSplashScreen = false` and manually hiding the splash screen with the `.hide()` method when the game has finished loading?

Android 12 Splash Screen:
> Duration: We recommend not exceeding 1,000 ms on phones. You can use a delayed start, but this can’t be longer than 166 ms. If the app startup time is longer than 1,000 ms, consider a looping animation.

I am not sure what happens in cases where the app is delayed longer than anything listed above but I suspect it leads to ANR. Also in regards to looping animation, I haven't tested this, don't know if that will help in any way if implemented, and it might be related to AVD which was not implemented until API 25.

If my memory is correct, the previous splash screen plugin was just an image overlaying the WebView. Since the Activity would have already been loaded before the Splash Screen displayed, I suspect this is why ANR was not an issue.

But, as Google is now forcing the new Splash Screen for all Android 12+ devices, I believe you seeing ANR because the game loading could be holding up the Activity. 

Again, this is an assumption based on how you configured Splash Screen. And again I haven't fully investigated all information so there could be something off.

If the assumption on how you're hiding the Splash Screen is correct, could you try setting `AutoHideSplashScreen = true` and see what happens with ANR?

Maybe creating a loading screen will be required and displaying it while the game is loading, but do not use the Splash Screen as the loading process.

E.g Splash Screen -> Loading Screen -> Game 

Anyways, I am just thinking a loud and hopefully, some of this might be useful.

I also want to point out that you might want to create an ANR trace? Not sure if this will help us.

https://developer.android.com/topic/performance/vitals/anr#pull_a_traces_file

**Comment by AshleyScirra** [comment] 2022-10-19 14:53
> Are you using the Splash Screen configurations AutoHideSplashScreen = false and manually hiding the splash screen with the .hide() method when the game has finished loading?

Construct does indeed configure Android apps that way. It never used to be a problem with cordova-android@10.x, but your explanation could be the reason for it triggers slow start/ANR.

It seems weird to me that a long splash screen would count as ANR. It didn't used to. Perhaps this is in fact an issue with Google's new splash screen implementation registering a false positive ANR? I guess we could work around it, but it seems weird - are we supposed to reimplement the splash screen in the app code so we can keep showing the same thing without triggering an ANR?

**Comment by breautek** [comment] 2022-10-19 15:20
Actually, the ANR might not be related the splashscreen at all (well it could still be... I guess, considering the issue seems to only occur with the new splashscreen system), according to the [Android Docs](https://developer.android.com/topic/performance/vitals/anr), ANRs are triggered if the UI thread has been blocked for too long.

> When the UI thread of an Android app is blocked for too long, an "Application Not Responding" (ANR) error is triggered.
> ...
>ANRs are a problem because the app’s main thread, which is responsible for updating the UI, can’t process user input events or draw, causing frustration to the user. For more information on the app’s main thread, see [Processes and threads](https://developer.android.com/guide/components/processes-and-threads).
> An ANR will be triggered for your app when one of the following conditions occur:
>
> - While your activity is in the foreground, your app has not responded to an input event or [BroadcastReceiver](https://developer.android.com/reference/android/content/BroadcastReceiver) (such as key press or screen touch events) within 5 seconds.
> - While you do not have an activity in the foreground, your [BroadcastReceiver](https://developer.android.com/reference/android/content/BroadcastReceiver) hasn't finished executing within a considerable amount of time.

**Comment by AshleyScirra** [comment] 2022-10-20 11:18
Do you think it's related to this issue?: https://issuetracker.google.com/issues/230236390

It does sound like the new splash screen implementation is counting towards slow cold start and possibly ANRs. What should we do about it? Hard code the splash screen to hide after 1 second and just show some other kind of intermediate loading screen? It seems weird that we have to essentially reimplement the splash screen just to fix some metrics...

**Comment by KekGames** [comment] 2022-10-24 10:09
I tested the game:
`AutoHideSplashScreen = true` and 5000ms fade-out time - ANRs and slow starts occur
`AutoHideSplashScreen = true` and 500ms fade-out time - no ANRs/slow starts (but there are a few seconds of black screen after splash while the game is loading)

**Comment by breautek** [comment] 2022-10-25 17:35
I think it's sufficient to say that delaying the splashscreen indeed counts towards ANR.

I'm not certain if there is a way around this either. It sounds like using the splashscreen as your loading view is not a good solution anymore with Google's splashscreen.

> Hard code the splash screen to hide after 1 second and just show some other kind of intermediate loading screen? It seems weird that we have to essentially reimplement the splash screen just to fix some metrics...

Quite frankly, Google's own example in their documentation does just this. See [Figure 1](https://developer.android.com/develop/ui/views/launch/splash-screen) where app launch shows the Gmail splashscreen, then proceeds with a dummy "loading" screen with placeholder labels.

In a context of loading game assets, the UI placeholder style may not make much sense, but the point here is to signal feedback to the user that something is indeed happening. So for games that spends time loading game assets for example may use a screen with a progress bar, showing that something is actually happening.

**Comment by breautek** [comment] 2022-12-02 12:44
I'm closing this issue because I think we have determined that delaying the splashscreen for too long Google will consider it as an ANR. So using the splashscreen has a loading screen is no longer ideal and will require apps to update and change the behaviour.

Android's ANR detection is looking for the first paint by the application or anything that blocks the UI thread for an extended period of time. Delaying the splashscreen delays the first paint which is what triggers the ANR and it seems like this is intentional. So apps should update and strive to show their own loading screen as quickly as possible and only keep the splashscreen alive for a short time. Having the app have their own loading screen should pass the ANR detection checks as it will appear that your app is responsive since it is painting UI updates, etc.

**Closed by breautek** 2022-12-02 12:44 UTC

**Comment by KekGames** [comment] 2022-12-02 13:06
@breautek delaying it for too long definititely makes it worse. 
Too add a bit more information: if I show it for just 500ms without waiting for the game to load (or even comment out postMessage completely) - it still produces ANR rate around the bad behaviour threshold (some days it's lower than 0.49%, other days it's higher). Before the update it was 0%-0.1%. I hadn't noticed any difference between 1.5s wait and 0s wait, nor any difference between compressed and uncompressed assets. Maybe showing loading screen as soon as possible, as you suggest, would solve the issue, but I can't test it until Construct 3 team adds this feature.

**Comment by breautek** [comment] 2022-12-02 13:30
I'm **pretty** confident based on my reading and understanding of the ANR that what I described is accurate.

This section on the Android [splashscreen docs](https://developer.android.com/develop/ui/views/launch/splash-screen/migrate#remove_the_custom_splash_screen_activity) also states loading up what is truely necessarily to launch the app, and then lazy load all the other app modules later.

> Lazy load your components, modules, or libraries: Avoid loading or initializing components or libraries that are not required for the app to work at launch, and load them later when the app needs it.
>
>If your app truly needs a component to work properly, load it only when it’s really needed and not at launch time, or use a background thread to load it after the app has started. Try to keep your Application onCreate() as light as possible.

If you find that it does not help after Construct 3 team provides the feature, then don't hesitate to let me know and we can reopen this issue.
