### ISSUE TITLE
Tools directory is now obsolete in Android SDK

### ISSUE THREAD

**Issue by markwaldin** [apache/cordova-android#944] opened 2020-04-05 19:07 UTC
# Bug Report

Documentation for installing suggest adding a path to Android sdk tools and tools/bin folder but the tools folder is obsolete in the current Android sdk

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment] 2020-04-05 20:20
Can you link to further information which state that the folder is obsolete?

**Comment by markwaldin** [comment] 2020-04-05 23:44
the page that declares the sdk tools as deprecated is here:

https://developer.android.com/studio/releases/sdk-tools

in addition Android Studio, Android SDK Manager marks the package as obsolete

**Comment by breautek** [comment] 2020-04-06 01:27
Thanks for taking the time to report this issue, however this is already reported in the our docs repo.

Duplicate of https://github.com/apache/cordova-docs/issues/1065

**Closed by breautek** 2020-04-06 01:27 UTC
