### ISSUE TITLE
Issues after upgrading the angular from 8.0.3 to 8.1.0 

### ISSUE THREAD

**Issue by soorireddy** [apache/cordova-android#763] opened 2019-07-09 12:12 UTC
app is working  well for angular **8.0.3**
getting blank screen after upgrading to 8.1.0 in android
**But 8.1.0 is working well in cordova-browser.**

not sure the issue is with angular / cordova-angular ?
Any help would be highly appreciated.

@angular/animations                  8.0.3  →    8.1.0
 @angular/cdk                         8.0.1  →    8.0.2
 @angular/common                      8.0.3  →    8.1.0
 @angular/compiler                    8.0.3  →    8.1.0
 @angular/core                        8.0.3  →    8.1.0
 @angular/forms                       8.0.3  →    8.1.0
 @angular/material                    8.0.1  →    8.0.2
 @angular/platform-browser            8.0.3  →    8.1.0
 @angular/platform-browser-dynamic    8.0.3  →    8.1.0
 @angular/router                      8.0.3  →    8.1.0
 @angular-devkit/build-angular      0.800.6  →  0.801.0
 @angular/cli                         8.0.6  →    8.1.0
 @angular/compiler-cli                8.0.3  →    8.1.0
 @angular/language-service            8.0.3  →    8.1.0
 @types/node                        12.0.10  →   12.6.1
 typescript                           3.4.3  →    3.5.3

**Comment by janpio** [comment] 2019-07-09 12:29
Have you remote debugged your app to look at the console for errors? https://ionic.zone/debug/remote-debug-your-app

**Comment by thanhphuocdang** [comment] 2019-07-22 05:49
I am running in the same issue, any solution?

**Comment by timbru31** [comment] 2019-07-22 20:05
Without a reproducible example debugging for us is much harder.

Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by thanhphuocdang** [comment] 2019-07-23 02:05
https://stackoverflow.com/questions/56606789/angular-8-ng-build-throwing-mime-error-with-cordova
Here is the current situation.

**Comment by breautek** [comment] 2019-07-23 03:29
> Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

If this error is what you are receiving, it is because a `<script type="module">` is being used and the responding server to load the script does not respond with the proper heads. It requires `Content-Type: text/javascript` header to be set.

Not sure if there is anything that can be done at the `cordova-android` level here... as I don't think we can disable the Strict MIME type check.

**Comment by helzgate** [comment] 2019-08-22 16:45
After changing the target in tsconfig.json from es2015 to es5 it now works.  No idea what if anything this breaks.

[See this SO article](https://stackoverflow.com/questions/56606789/angular-8-ng-build-throwing-mime-error-with-cordova)

**Comment by jcesarmobile** [comment] 2019-09-20 23:02
The problem is scripts with type="module" and with nomodule don't work from file protocol, you have to use only one script without type="module" and without nomodule. See previous comments and links, some of them explain how to configure angular to build like that.
This is not a cordova-android issue, closing

**Closed by jcesarmobile** 2019-09-20 23:02 UTC
Labels: info-needed, support

**Comment by achalj09** [comment] 2019-11-13 05:02
After 2 days of constantly research, finally got this, thanks a lot, really appreciated

**Comment by helzgate** [comment] 2019-11-13 13:18
### Update:  
I was able to go back to using `"target": "es2015"` in my tsconfig.json by changing my browserlist file to the following:

```
#> 0.5%
Chrome >= 70 and Chrome <= 72
#last 2 versions
#Firefox ESR
#not dead
#not IE 9-11 # For IE 9-11 support, remove 'not'.
```
Please play around with these options because I have no clue what I'm doing, I just found that it works.

**Comment by Arbaaz-hub** [comment] 2020-07-04 07:07
Thanx to all after long time i got the answer
