### ISSUE TITLE
Execution failed for task ':app:mergeDebugResources'.

### ISSUE THREAD

**Issue by GoldHatGamer** [apache/cordova-android#1250] opened 2021-07-01 14:23 UTC
# Bug Report

### What is expected to happen?
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2InternalException: AAPT2 aapt2-3.3.0-5013011-linux Daemon apache/cordova#6: Daemon startup failed
  This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21m 15s
20 actionable tasks: 20 executed
/root/hello/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2InternalException: AAPT2 aapt2-3.3.0-5013011-linux Daemon apache/cordova#6: Daemon startup failed
  This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

### Environment, Platform, Device
I using ubuntu in termux 
My device redmi Y2 

### Version information

Cordova: Cordova CLI
Operating System: Ubuntu arch x86

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by coolscene** [comment] 2021-07-27 18:52
Same/similar issue here. In my case, I've found the problem is all <edit-config> and <config-file> can only be run once when building. After building it once and the edit configs and config files are applied (in this case to the AndroidManifest.xml), commenting/removing them from the config.xml seems to fix the compiling issue.

**Comment by mleech** [comment] 2022-02-17 04:14
I had the same issue and finally found a solution in a comment to a blog post here : https://www.damirscorner.com/blog/posts/20171117-CustomizingAndroidManifestInCordova.html#comment-4550864745

Adding the attribute `xmlns:android="http://schemas.android.com/apk/res/android"` to the `<widget>` element in `config.xml` fixed it.

**Comment by igorsantos07** [comment] 2022-02-21 03:05
I'm also facing the exact same output as reported, and have spent several hours mix and matching Android/Java tools and versions, to no avail. Google results usually point to Gradle/aapt bugs from 2021 which doesn't seem to apply since I'm on more recent versions. The XML suggestion above didn't make any difference, and the other suggestion... no idea what it means :(

Any guidance on how to proper start debugging? Finding issues with Android/Java tools is hard when you're a developer on other stacks...
I wasn't able to find what actual task was being ran from `gradlew`, since the "command failed" hint seems incomplete.

- Linux Mint 20.2
- (system) gradle 4.4.1 (the one that runs `gradlew` seems to be 4.10)
- I don't have a JVM installed globally now, but I already had JDK 11 and JDK 16. I had the same errors. Things seems to be running from Android Studio JDK, which should be v16. Gradle reports JVM 1.8.0_312
- cordova-android 8.1.0
- build-tools v33-rc1 and v32 (had to install v32 because the latest, which is rc1, didn't seem to be recognized by the cordova version checker?)
- rest of Android tools installed via SDK (either manually on my first tries, or via Android Studio later):
  - cmake;3.18.1
  - cmdline-tools;latest   | 6.0
  - emulator               | 31.2.8
  - patcher;v4
  - platform-tools         | 32.0.0
  - platforms;android-28, 29, 32
  - sources;android-28, 29

**Comment by breautek** [comment] 2022-05-17 19:18
> This should not happen under normal circumstances, please file an issue if it does.

This is an error coming from Gradle, so the bug report should be made against gradle.

To get more information for a gradle bug report, from `platforms/android` directory, you can run `./gradlew app:buildDebug --info --stacktrace`.

For this reason I'm closing this issue. However if there is a specific cordova configuration that doesn't work, a new issue can be reported with a [minimal reproduction](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) and we can take a look.

**Closed by breautek** 2022-05-17 19:18 UTC

**Comment by raldincasidar-studio** [comment] 2023-08-03 10:25
> I had the same issue and finally found a solution in a comment to a blog post here : https://www.damirscorner.com/blog/posts/20171117-CustomizingAndroidManifestInCordova.html#comment-4550864745
> 
> Adding the attribute `xmlns:android="http://schemas.android.com/apk/res/android"` to the `<widget>` element in `config.xml` fixed it.

this works guys!

**Comment by vinaythapa1** [comment] 2023-08-07 15:57
I had the same issue and finally found a solution in a comment to a blog post here : https://www.damirscorner.com/blog/posts/20171117-CustomizingAndroidManifestInCordova.html#comment-4550864745

Adding the attribute xmlns:android="http://schemas.android.com/apk/res/android" to the <widget> element in config.xml fixed it.

Thanks it is working.
