### ISSUE TITLE
Gradle Fails to sync after upgrading to Cordova Android 8.0

### ISSUE THREAD

**Issue by echonox** [apache/cordova-android#675] opened 2019-02-17 13:58 UTC
# Bug Report

### What is expected to happen?
The Gradle should sync with success

### What does actually happen?
Gradle Sync Fails

## Information

After upgrading to Cordova Android 8.0 Gradle sync fails with the following message:

```
API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Open Manifest File
Move minSdkVersion to build file and sync project

The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.

The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Open Manifest File
Move minSdkVersion to build file and sync project
```

### Command or Code

Open the platforms/android project in Android Studio

### Version information

Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
Cordova: 8.1.2
Cordova Android: 8.0
Cordova Plugins: 
cordova-plugin-awesome-shared-preferences 0.1.0 "Shared preferences"
cordova-plugin-backbutton 0.3.0 "Backbutton"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-calendar 5.1.4 "Calendar"
cordova-plugin-deeplinks 1.1.0 "Cordova Deeplinks Plugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-firebase-crashlytics 0.0.8 "Cordova Firebase Crashlytics Plugin"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by geoffliddiard** [comment] 2019-02-18 12:22
Also seeing this issue. Rolling back to cordova-android@7.1.4 until a fix is released

**Comment by janpio** [comment] 2019-02-18 16:41
Thanks for the report.

Can you provide a bit more information? Is this for existing projects that are upgraded? How exactly do you upgrade? How do you usually build this project, only with Android Studio? Is it reproducible with a new Cordova project?

**Comment by noledgy** [comment] 2019-02-18 23:08
I am able to reproduce this in my upgraded project. I was having the same problem with the previous release (I think 7.1.4).
I created a simple new project, then imported it into Android Studio. Same warnings/errors. It does not appear to be related to upgrades. Very easy to reproduce.

**Comment by Crylion** [comment] 2019-02-19 09:14
Also experiencing this. The cordova build on the command line works fine, just opening it in Android Studio produces the errors. Android Studio provides a one-click refactor that moves the minSdk entry from the manifest, but that's still a manual step I have to take.

**Comment by janpio** [comment] 2019-02-19 09:53
So can one recreate it by creating a new Cordova project with cordova-android 8.0 and then just opening the project in Android Studio 3.2.1 (or also other versions)?

**Comment by rossholdway** [comment] 2019-02-19 19:15
@janpio I can recreate this by removing all platforms and plugins, then `cordova prepare`. Opening the the project in Android 3.3.1 displays the Gradle sync issues above.

**Comment by janpio** [comment] 2019-02-19 20:11
Can you try to confirm a reproduction that starts with `cordova create`? That would be easiest for someone to look into.

**Comment by noledgy** [comment] 2019-02-19 21:07
create MyTest
cordova platform add android@8.0.0
cordova build
Start Android Student (3.3.1)
Just importing, wsync failed:

ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
Move minSdkVersion to build files and sync project
Affected Modules: CordovaLib, app

Remove minSdk from CordovaLib and app manifest
Rebuild project get error
Close and re-open Android Studio
Popup comes up telling you upgrade to Android Gradle plugin to version 3.3.1 and Gradle to version 4.10.1. Do it.

Build now runs

**Comment by echonox** [comment] 2019-02-24 08:47
> Thanks for the report.
> 
> Can you provide a bit more information? Is this for existing projects that are upgraded? How exactly do you upgrade? How do you usually build this project, only with Android Studio? Is it reproducible with a new Cordova project?

I tried:
1. Using new project `cordova create`
2. Removing the platform (7.1.4) and installing the latest (8.0.0)

both ways I get gradle sync issue, with cordova build/run I don't have that problem

**Comment by sagrawal31** [comment] 2019-02-25 07:48
Any workaround while the #680 is merged.

**Comment by echonox** [comment] 2019-02-25 12:03
> Any workaround while the #680 is merged?

I've just clicked the link in the error message to "move" the minSdk, and I was able to build from android studio after that

**Closed** 2019-04-06 04:28 UTC
Labels: question, support, version: 8.0.0

**Comment by cvasanthcmail** [comment] 2019-06-26 09:44
save my life

**Comment by cvasanthcmail** [comment] 2019-06-26 09:45
> 
> 
> ```
> create MyTest
> cordova platform add android@8.0.0
> cordova build
> ```
> 
>     * Start Android Student (3.3.1)
> 
> 
> Just importing, wsync failed:
> 
> ```
> ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.
> Move minSdkVersion to build files and sync project
> Affected Modules: CordovaLib, app
> ```
> 
>     * Remove minSdk from CordovaLib and app manifest
> 
>     * Rebuild project get error
> 
>     * Close and re-open Android Studio
> 
>     * Popup comes up telling you upgrade to Android Gradle plugin to version 3.3.1 and Gradle to version 4.10.1. Do it.
> 
> 
> Build now runs

Thanq...    save my life

**Comment by arashmad** [comment] 2019-08-13 14:57
@echonox It works for me.
