### ISSUE TITLE
androidx

### ISSUE THREAD

**Issue by janpio** [apache/cordova-android#565] opened 2018-11-18 22:44 UTC
Just learned about `androidx`, this new package name Google uses or will use for support libraries and similar stuff:

https://stackoverflow.com/questions/51280090/what-is-androidx
https://developer.android.com/jetpack/androidx/

Will this affect cordova-android?

**Comment by dpogue** [comment] 2018-11-19 20:38
The short answer is no, at least for now. The existing support library will continue to exist for the foreseeable future, so cordova-android should be fine.

However, we should probably look into migrating to AndroidX with a major version bump. We can't do it sooner, because AndroidX is only available when targeting Android 9 and higher.

Also worth noting that there's an AndroidX WebView compatibility library, but we can't use it until we drop support for Android 4.4 (which is **not** happening in the next major)

**Comment by brodybits** [comment] 2018-11-19 20:48
I did take a look, started composing an answer while working on something else.

My impression from <https://android-developers.googleblog.com/2018/05/hello-world-androidx.html> is that `androidx` is only used for "unbundled" Java package namespaces (Java packages), meaning part of the SDK and not part of the Android system libraries. The Java code only *seems* to use the affected Java packages in `test/app/src/androidTest`, which I think should not affect any Cordova Android app developers in case we or they decide to use AndroidX someday.

(My trick was to search all Java files in cordova-android for "import com.android", "import android.arch", "import android.databi", and "import android.supp", according to affected namespaces described in <https://developer.android.com/jetpack/androidx/migrate>)

**Comment by dpogue** [comment] 2018-11-19 20:56
Some plugins (i.e., [camera](https://github.com/apache/cordova-plugin-camera/blob/master/plugin.xml#L86)) have to use the support library for dealing with FileProviders

**Comment by brodybits** [comment] 2018-11-19 20:58
Would this be more plugin-specific then?

I wonder if we could support AndroidX vs old style in a separate plugin for a while?

**Comment by davidschreiber** [comment] 2019-01-16 18:39
Hi there 👋I'd like to better understand the current schedule for the AndroidX migration of `cordova-android`.

We (the team at PSPDFKit, and maintainers of [PSPDFKit/Cordova-Android](https://github.com/PSPDFKit/Cordova-Android)) have previously upgraded our Android library to AndroidX (as many of our customers did with their apps and libraries too). We're currently getting reports of Cordova users that fail to upgrade due to the lack of AndroidX support in `cordova-android`. We've performed a brief analysis of the current situation, and thought it might be interesting for you as well.

There's a couple of factors that should considered for your schedule for migrating to AndroidX:

* Development of the support libraries has been halted and the old support libraries have officially been deprecated. In the next couple of weeks/months, most Android libraries and apps that used the support libs will migrate to AndroidX (if they haven't done so already). The incompatibility we discovered with our own wrapper is probably just the beginning, and `cordova-android` will have to follow this trend to stay compatible with the Android ecosystem. A migration has to happen, the question is when it should be done.

* Moving to AndroidX is a breaking change for Cordova, so it should probably be part of the next major update (9.x). While for normal Android apps upgrading to AndroidX is a soft-migration (using Google's automated [Jetifier migration](https://developer.android.com/jetpack/androidx/migrate#migrate) which auto-migrates old `.class` files that use the support libs over to AndroidX) this migration strategy does not work for Cordova, which is built around plugins that ship as `.java` source files. Jetifier was not designed for such a plugin system, and does not operate on source files, which means that all Cordova plugins need to be migrated manually in order to work. 

* Integrating AndroidX and the support libraries into a single app does not work. While most classes inside AndroidX have been renamed and are now inside the `androidx.*` package, some legacy code is still inside the old support package names, which will cause build errors when trying to integrate both libraries side by side.

* Migration to AndroidX will require updates to the Android part of several official Cordova plugins. I don't have an extensive list of plugins that use the support libs yet, but I believe that the effort to migrate these should be manageable. From our experience, migrating works automatic for most parts using Android Studio, or is a matter of search and replace using any other tool.

Are there any concrete plans for migration to AndroidX so far, and if so, could you share them with us? Any feedback would be highly appreciated.

**Comment by brodybits** [comment] 2019-01-16 20:04
> We're currently getting reports of Cordova users that fail to upgrade due to the lack of AndroidX support in `cordova-android`.

@davidschreiber it would really help if you could explain what exactly is going wrong. I tried to explain in <https://github.com/apache/cordova-android/issues/565#issuecomment-440036712> that none of the code in this project ([`cordova-android`](https://npmjs.com/package/cordova-android)) should be affected by the `androidx` updates. The one possible exception is some testing code in `test/app/src/androidTest`, which should not be part of the generated Cordova Android project.

I took a quick look through README.md in <https://github.com/PSPDFKit/Cordova-Android> and noticed that it needs the nightly release of cordova-android@8. You can see in apache/cordova#10 that we are in the process of finishing and releasing the Cordova 9 major release so that your users will no longer need the nightly release. Also the requirement for cordova-android@8 should have triggered a major release since it was a breaking change

**Comment by davidschreiber** [comment] 2019-01-17 07:56
Hi @brodybits. Thanks for the feedback. You're absolutely right that this is not a specific issue to the code inside `cordova-android` but relevant for the next major version bump of Cordova plugins. However, since it only affects Android I took the chance to comment on this issue, which seemed to me like an "umbrella issue" for the general migration topic.

> @davidschreiber it would really help if you could explain what exactly is going wrong.

The specific issue our customers are facing is a D8 build time error which comes from including Cordova plugins that still use the support libraries (in this specific case the `cordova-plugin-camera`) while also including plugins that contain AndroidX libraries. As you mentioned, this is not specific to code inside `android-cordova`.

> I took a quick look through README.md in https://github.com/PSPDFKit/Cordova-Android and noticed that it needs the nightly release of cordova-android@8. You can see in apache/cordova#10 that we are in the process of finishing and releasing the Cordova 9 major release so that your users will no longer need the nightly release.

Thank you very much for the heads-up. It's great to hear that the update to Cordova 9 is progressing well, and we're looking forward to the stable release of it.

I'm sorry if I misunderstood the scope of Cordova 9. Do I now understand it correctly, that major releases of `cordova` and `cordova-android` are not strictly tied to upgrades of the official plugins? If that is the case, I would go ahead and create AndroidX migration issues in the specific plugin repos (and probably also prepare PRs if this is desired).

**Comment by janpio** [comment] 2019-01-17 11:43
> Do I now understand it correctly, that major releases of cordova and cordova-android are not strictly tied to upgrades of the official plugins? If that is the case, I would go ahead and create AndroidX migration issues in the specific plugin repos (and probably also prepare PRs if this is desired).

Yes + Yes please!

**Comment by jcesarmobile** [comment] 2019-01-23 23:46
https://github.com/apache/cordova-plugin-camera/issues/405

**Comment by brodybits** [comment] 2019-01-28 01:17
> The specific issue our customers are facing is a D8 build time error which comes from including Cordova plugins that still use the support libraries (in this specific case the `cordova-plugin-camera`) while also including plugins that contain AndroidX libraries.

I would be grateful if someone could post a demo project. I already spent almost half a day without success using AndroidX from a Cordova-Android project.

**Comment by brodybits** [comment] 2019-01-31 14:59
@davidschreiber I really appreciate your efforts to help resolve this issue, especially in <https://github.com/apache/cordova-plugin-camera/pull/418>. I am very sorry that it has not proven to be so easy to resolve the issue with AndroidX in Cordova.

I think you pointed out a very important issue with the compile SDK version (#631), which should be resolved before we continue with AndroidX support.

I cannot promise when I will get a chance to resolve #631 due to some other priorities and commitments.

**Comment by steipete** [comment] 2019-04-06 11:56
Hi! Just checking on the status of AndroidX and the Cordova ecosystem.
Are there any guidelines or roadmap plans by now? (I'd like to relay that to one of our partners that use our wrapper). Thanks!

**Comment by brodybits** [comment] 2019-04-08 00:36
New Cordova 9 release has been shipped.

As discussed before, the only possible issue with AndroidX is in the plugins. I think it would be good to get this resolved before we ship the major release of the plugins.

The one plugin where I could see this issue is `cordova-plugin-camera`. Someone has already raised a PR in apache/cordova-plugin-camera#418 but it seems to be waiting for some rework.

I personally do not have so much time to work on this issue due to some other priorities.

**Comment by brodybits** [comment] 2019-04-24 17:13
@davidschreiber @steipete did you guys see [`dpa99c/cordova-plugin-androidx`](https://github.com/dpa99c/cordova-plugin-androidx) that @dpa99c posted in <https://github.com/apache/cordova/issues/69#issuecomment-485553425>?

From <https://github.com/apache/cordova/issues/69#issuecomment-485553425> it sounds like [`dpa99c/cordova-plugin-androidx`](https://github.com/dpa99c/cordova-plugin-androidx) may be needed to work reliably with AndroidX. I would love some more feedback if this proves to be the case or not.

I wonder if we should integrate the changes from [`dpa99c/cordova-plugin-androidx`](https://github.com/dpa99c/cordova-plugin-androidx) into cordova-android someday?

**Comment by dpogue** [comment] 2019-04-24 17:21
I think I agree with the idea that the next major version of Android should be set up to use AndroidX in gradle, and all plugins using Android Support Libraries should be migrated to AndroidX.

**Comment by dpa99c** [comment] 2019-04-24 17:35
@dpogue Until such time as plugin authors have updated their plugins to migrate to AndroidX, it should be possible to use [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) to migrate their legacy plugin code in-place inside a Cordova Android project.

**Comment by timbru31** [comment] 2019-04-24 18:53
I’ve installed it today for our app and so far it works great 👍

**Comment by Be4t5** [comment] 2019-06-18 19:01
> @dpogue Until such time as plugin authors have updated their plugins to migrate to AndroidX, it should be possible to use [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) to migrate their legacy plugin code in-place inside a Cordova Android project.

Thank you! You are a lifesaver! I was going to start editing each plugin by hand and I found your message :) :)

**Comment by florianmonfort** [comment] 2019-12-16 03:06
Hi all,

It seems a lot of plugins still have issues despite the androidx plug in that @dpa99c has created. The problem is these plugins are used for critical functions of our app and we can't get Android Studio to compile or even within the command line. I have opened bug reports in each of the different repositories for this but besides that we have found no solution and we can't publish any new app updates anymore and don't know what to do:

https://github.com/apache/cordova-plugin-camera/issues/539
https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/489
https://github.com/apache/cordova-android/issues/881

There is also some weird issue where after adding android to the cordova platforms every time we open with Android Studio there is an issue with the gradle file having some weird 27.+ line that gradle doesn't like. We also have no idea why cordova does this and haven't found any info anywhere.

If @Be4t5 , @timbru31 @brodybits have any suggestions on how to fix this it would be highly appreciated.

**Closed** 2020-01-27 06:52 UTC
Labels: info-needed

**Comment by wf9a5m75** [comment] 2020-05-30 23:49
`cordova-plugin-androidx-adapter` does not work on PhoneGap build. It means this solution is not perfect for me.

That's why I re-created another plugin, which is written in `gradle` script.
[cordova-androidx-build](https://github.com/wf9a5m75/cordova-androidx-build)

The purpose of this plugin is little different from `cordova-plugin-androidx-adapter`.
`cordova-plugin-androidx-adapter` migrates the project code from `Android Support Libraries` to `AndroidX libraries`, which is one way.
This is OK for general developers. 

However plugin developers have to support both environments for a while (`cordova-android@8` and `cordova-android@9`).

That's why this plugin migrates from `AndroidX libraries` to `Android Support Libraries` if the environment does not support `AndroidX`.

![work-flow](https://user-images.githubusercontent.com/167831/83340259-c2773400-a28a-11ea-8bb5-56d4a1a170fe.png)

And this plugin uses `Gradle` script, works on PC and cloud services.
If you are interested in, please try it


|                                  | cordova-plugin-androidx-adapter | cordova-androidx-build    |
|----------------------------------|---------------------------------|---------------------------|
| `support library` -> `AndroidX`  |  :white_check_mark:             | :white_check_mark:        |
| `support library` <- `AndroidX`  |  :x:                            | :white_check_mark:        |
| work on PC                       |  :white_check_mark:             | :white_check_mark:        |
| work on cloud services           |  :x:                            | :white_check_mark:        |
| when execute the process         |  after `cordova prepare`        | gradle sync               |
| mechanism                        |  `cordova hook script`          | gradle                    |
