### ISSUE TITLE
<preference name="android-targetSdkVersion" value="30" /> not working and keep asking for 29

### ISSUE THREAD

**Issue by almothafar** [apache/cordova-android#1178] opened 2021-03-26 12:58 UTC
# Bug Report

## Problem
It seems setting targetSdkVersion to 30 not working, it sounds like the same issue as the one closed #846 , I set `<preference name="android-targetSdkVersion" value="30" />` in config.xml and I installed only `platform-30` it keeps asking me to install version 29:

```console
#13 394.1 Checking the license for package Android SDK Platform 29 in /opt/android-sdk-linux/licenses
#13 394.1 License for package Android SDK Platform 29 accepted.
#13 394.1 Preparing "Install Android SDK Platform 29 (revision: 5)".
#13 394.1 Warning: Failed to read or create install properties file.
#13 394.2
#13 394.2 FAILURE: Build failed with an exception.
#13 394.2
#13 394.2 * What went wrong:
#13 394.2 Could not determine the dependencies of task ':app:bundleReleaseResources'.
#13 394.2 > Failed to install the following SDK components:
#13 394.2       platforms;android-29 Android SDK Platform 29
#13 394.2   Install the missing components using the SDK manager in Android Studio.
```

There is no other information to put but it is the same issue as #846 nothing new.

### Version information
What are relevant versions you are using?
Latest everything, Cordova 10 and cordova-android 9.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by goodjun** [comment] 2021-04-04 07:06
you can try
```
ionic cordova platform add android@version
```

**Comment by almothafar** [comment] 2021-04-04 09:49
@goodjun You totally missed the point, I have it already on the latest version (9.0.0) the problem is that the build process is ignoring the target platform, which is can be set and changed manually from Android studio but not in the command line, as for me I do that using dockerfile.

**Comment by breautek** [comment] 2021-04-04 13:04
I think this might be a cosmetic issue. I was using this the other day and despite the cordova build output stating using android-29, the final output of both an apk or app bundle still produced api 30 package.

Are you able to confirm you see the same behavior?

**Comment by almothafar** [comment] 2021-04-04 13:22
@breautek I edited my last comment to @goodjun 

Also, the build itself doesn't complete at all, I just have platform-30 installed not 29, make sure you don't have both, and try to build, it keeps asking for 29 to be installed and trying to install it.

**Comment by almothafar** [comment] 2021-04-04 22:50
@breautek  Ok I got what you are saying, so it seems the value is not ignored:

![image](https://user-images.githubusercontent.com/13887564/113523558-c82b5d80-95b0-11eb-9cb7-f46cb4779547.png)

That's If I installed 29, but If I installed platform 30, I get the error.

**Comment by almothafar** [comment] 2021-04-04 23:01
I saw the following lines in generated build.gradle file (note that I installed build-tools version 30.0.3, not 29.0.2):

![image](https://user-images.githubusercontent.com/13887564/113523773-a3d08080-95b2-11eb-96fd-3246301fbc25.png)

And in the project.properties file:
 
![image](https://user-images.githubusercontent.com/13887564/113523794-bf3b8b80-95b2-11eb-8124-225882115603.png)

So is this the reason behind the issue?

**Comment by almothafar** [comment] 2021-04-04 23:06
@breautek I just updated develop branch here https://github.com/capellasolutions/ionic-cordova-docker/tree/develop so you can run `build-mobile.sh` and choose Android when it asks for it and you will see that issue:

![image](https://user-images.githubusercontent.com/13887564/113523887-8d76f480-95b3-11eb-8405-b26061650fe2.png)

**Comment by shanlin2dltk** [comment] 2021-04-05 17:49
Adding to the importance of resolving this issue is very soon Google store won't accept submission of [sdk level less than 30](https://developer.android.com/distribute/best-practices/develop/target-sdk).

**Comment by AuTiiTo** [comment] 2021-04-05 20:02
We'll need to update this version in the near future.

**Comment by breautek** [comment] 2021-04-06 04:40
> Adding to the importance of resolving this issue is very soon Google store won't accept submission of [sdk level less than 30](https://developer.android.com/distribute/best-practices/develop/target-sdk).

This is not related to this issue. Targeting API 30 still works via `android-targetSdkVersion` preference, so that's not a problem. Additionally we will bump our default target SDKs on our major releases to match the requirement of Google Play store.

The issue described in this ticket is Cordova will still attempt to the default platform SDK (currently API 29) even when targetSdkVersion is set to a different API level. **So the current workaround is to simply have both platform 29 & 30 installed.** 

I've had a chance to do some digging on the cause and I've found 3 things that Cordova tooling must do:

### (1) Ensure compileSdkVersion matches targetSdkVersion 

`compileSdkVersion` is the SDK that the application is compiled against, while the `targetSdkVersion` is an assertion that you've tested your application at the target SDK level for compatibility. If the platform API level is higher of the target, then the platform will enable backwards-compatibility behaviours.

There isn't any real reason to have a `compileSdkVersion` set that is different than the `targetSdkVersion` and doing so can cause an unstable application. Currently, the `android-targetSdkVersion` overrides but doesn't modify `compileSdkVersion` creating this possibility. Cordova should force `compileSdkVersion` and `targetSdkVersion` to be equal.

There is currently no `config.xml` preference to set the `compileSdkVersion`, and the lack of this feature should remain. There is a [cdvCompileSdkVersion](https://cordova.apache.org/docs/en/10.x/guide/platforms/android/index.html#setting-gradle-properties) cordova gradle flag, which I think should become deprecated and potentially removed in `cordova-android@10` and replaced with a `cdvTargetSdkVersion` flag to match the `config.xml`'s `android-targetSdkVersion` preference.

### (2) Ensure android/project.properties has the correct target

Currently, Cordova does not modify the `target` attribute inside `/platforms/android/project.properties` and it remains set to `android-29` which will cause the Android Gradle Plugin (AGP) to download Platform 29.

### (3) Ensure android/CordovaLib/project.properties has the correct target

Currently, Cordova does not modify the `target` attribute inside `/platforms/android/CordovaLib/project.properties` and it remains set to `android-29` which will cause AGP to download Platform 29.

All 3 actions must be done in order for the AGP to not download API 29.

ICYMI: You can workaround this issue by installing both Platform 29 & 30. You can still build APKs targeted against API 30.

**Comment by almothafar** [comment] 2021-04-06 12:55
>You can workaround this issue by installing both Platform 29 & 30. You can still build APKs targeted against API 30.

Actually, is enough to install platform-29, installing platform 30 won't be effective and pointless anyway because of other gradle project properties files, that what I was able to do and build using my docker file even with `android-targetSdkVersion` set t 30 as it is moved to `cdvTargetSdkVersion`

**Comment by breautek** [comment] 2021-04-06 13:24
> installing platform 30 won't be effective and pointless anyway because of other gradle project properties files,

As noted in my notes above but the workaround will still build a target 30 SDK, which will still enable API changes that API 30 will introduce.

If using API 30 platform SDK is a requirement, a temporary full workaround is to modify the following:

/platforms/android/project.properties:
```
target=android-30
```

/platforms/android/CordovaLib/project.properties:
```
target=android-30
```

Currently the compile SDK version is can be overrided using the `cdvCompileSdkVersion` flag e.g:
```
cordova build android --release -- --gradleArg=-PcdvCompileSdkVersion=30
```

Lastly, of course you still need the `android-targetSdkVersion` preference in your `config.xml` file:
```
<preference name="android-targetSdkVersion" value="30" />
```

Cordova may overwrite changes to files inside `/platforms/` so I'd advise crafting a `before_build` [hook](https://cordova.apache.org/docs/en/10.x/guide/appdev/hooks/index.html).

**Comment by AuTiiTo** [comment] 2021-04-06 15:41
hi again guys.
I did all the steps, how can I ensure that the platform is correct?
I searched and found that the command "gradle cdvPrintProps" show this properties:

task cdvPrintProps {
    doLast {
        println('cdvCompileSdkVersion=' + cdvCompileSdkVersion)
        println('cdvBuildToolsVersion=' + cdvBuildToolsVersion)
        println('cdvVersionCode=' + cdvVersionCode)
        println('cdvVersionCodeForceAbiDigit=' + cdvVersionCodeForceAbiDigit)
        println('cdvMinSdkVersion=' + cdvMinSdkVersion)
        println('cdvMaxSdkVersion=' + cdvMaxSdkVersion)
        println('cdvTargetSdkVersion=' + cdvTargetSdkVersion)
        println('cdvBuildMultipleApks=' + cdvBuildMultipleApks)
        println('cdvReleaseSigningPropertiesFile=' + cdvReleaseSigningPropertiesFile)
        println('cdvDebugSigningPropertiesFile=' + cdvDebugSigningPropertiesFile)
        println('cdvBuildArch=' + cdvBuildArch)
        println('computedVersionCode=' + android.defaultConfig.versionCode)
        android.productFlavors.each { flavor ->
            println('computed' + flavor.name.capitalize() + 'VersionCode=' + flavor.versionCode)
        }
    }
}

but it's showed me an error. Did you has another suggestion to see it?
Thanks again for all the effort :)

**Comment by almothafar** [comment] 2021-04-07 10:31
I was able finally to build it using `before_build` hook 
https://github.com/capellasolutions/ionic-cordova-docker/tree/develop/example-app/scripts

Until this issue is resolved here, maybe in cordova-android 10 or 9.something

**Comment by breautek** [comment] 2021-04-18 01:49
@almothafar I believe I have a working fix https://github.com/apache/cordova-android/pull/1212

Because the PR is based off of the new master which is a development version of `cordova-android@10`, which contains the SDK 30 by default, you can test it by setting `android-targetSdkVersion` to `29`.

You should set that API 29 and only API 29 is ever downloaded/used with that PR.

**Closed** 2021-07-06 06:38 UTC
Labels: bug

**Comment by Chamaraindrajith97** [comment] 2021-07-11 11:06
**Tested and it worked.**

I changed on config.xml to :

   ` <preference name="android-targetSdkVersion" value="30" />`

but it didn’t work so, I remove the platform by using :

   ` cordova platform remove android`

then add the latest cordova android version :

    `cordova platform add android@latest`

finally build the project : 

    `cordova build android`

It worked! Amazing.

You can check it by going to this file. 
\platforms\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml

**Comment by krunalsk007** [comment] 2021-07-24 12:19
Cordova released cordova android [10.0.0](https://cordova.apache.org/announcements/2021/07/20/cordova-android-10.0.0.html) on 20/7/2021 so now we can add android api 30 in our project.
`ionic cordova platform remove android
ionic cordova platform add android@10.0.0`

**Comment by krunalsk007** [comment] 2021-07-24 12:21
Cordova released cordova android 10.0.0 on 20/7/2021 so now we can add android api 30 in our project.
ionic cordova platform remove android
ionic cordova platform add android@10.0.0

**Comment by krunalsk007** [comment] 2021-07-24 12:22
Cordova released cordova android 10.0.0 on 20/7/2021 so now we can add android api 30 in our project. and its not asking for android 29.

`ionic cordova platform remove android`
`ionic cordova platform add android@10.0.0`

**Comment by Pumayk26** [comment] 2021-08-18 12:30
> 
> 
> **Tested and it worked.**
> 
> I changed on config.xml to :
> 
> ` <preference name="android-targetSdkVersion" value="30" />`
> 
> but it didn’t work so, I remove the platform by using :
> 
> ` cordova platform remove android`
> 
> then add the latest cordova android version :
> 
> ` cordova platform add android@latest`
> 
> finally build the project :
> 
> `cordova build android`
> 
> It worked! Amazing.
> 
> You can check it by going to this file.
> \platforms\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml

Hi Chamara... Did you able to compile your ionic app with sdk 30..? Am getting this annoying error message again and again... 

`C:\Users\User_App\platforms\android\app\src\main\java\org\apache\cordova\whitelist\WhitelistPlugin.java:63: error: cannot find symbol
            allowedRequests = new Whitelist();
                                  ^
  symbol:   class Whitelist
  location: class org.apache.cordova.whitelist.WhitelistPlugin
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.`

**Comment by almothafar** [comment] 2021-08-18 12:33
> > **Tested and it worked.**
> > I changed on config.xml to :
> > ` <preference name="android-targetSdkVersion" value="30" />`
> > but it didn’t work so, I remove the platform by using :
> > ` cordova platform remove android`
> > then add the latest cordova android version :
> > ` cordova platform add android@latest`
> > finally build the project :
> > `cordova build android`
> > It worked! Amazing.
> > You can check it by going to this file.
> > \platforms\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml
> 
> Hi Chamara... Did you able to compile your ionic app with sdk 30..? Am getting this annoying error message again and again...
> 
> `C:\Users\User_App\platforms\android\app\src\main\java\org\apache\cordova\whitelist\WhitelistPlugin.java:63: error: cannot find symbol allowedRequests = new Whitelist(); ^ symbol: class Whitelist location: class org.apache.cordova.whitelist.WhitelistPlugin Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details.`

remove whitelist plugin using `cordova plugin rm cordova-plugin-whitelist` it is mentioned on that plugin page https://github.com/apache/cordova-plugin-whitelist

**Comment by Pumayk26** [comment] 2021-08-18 13:18
> 
> 
> > > **Tested and it worked.**
> > > I changed on config.xml to :
> > > ` <preference name="android-targetSdkVersion" value="30" />`
> > > but it didn’t work so, I remove the platform by using :
> > > ` cordova platform remove android`
> > > then add the latest cordova android version :
> > > ` cordova platform add android@latest`
> > > finally build the project :
> > > `cordova build android`
> > > It worked! Amazing.
> > > You can check it by going to this file.
> > > \platforms\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml
> > 
> > 
> > Hi Chamara... Did you able to compile your ionic app with sdk 30..? Am getting this annoying error message again and again...
> > `C:\Users\User_App\platforms\android\app\src\main\java\org\apache\cordova\whitelist\WhitelistPlugin.java:63: error: cannot find symbol allowedRequests = new Whitelist(); ^ symbol: class Whitelist location: class org.apache.cordova.whitelist.WhitelistPlugin Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details.`
> 
> remove whitelist plugin using `cordova plugin rm cordova-plugin-whitelist` it is mentioned on that plugin page https://github.com/apache/cordova-plugin-whitelist

Thanks a lot... Am a noob to this ionic cordova stuff... You made my day dear... :)  Thanks again

**Comment by breautek** [comment] 2021-08-18 13:27
> remove whitelist plugin using cordova plugin rm cordova-plugin-whitelist it is mentioned on that plugin page

We are in an odd state right now because the current cordova CLI will auto-add the whitelist plugin when you create a new cordova project, which is deprecated and incompatible with the latest major version of cordova-android. The next major cordova CLI will solve this problem.

**Comment by danicholls** [comment] 2021-12-29 22:50
If you stick with Cordova 9.1.0 and update config.xml to target Android SDK version 30, you'll need to sign like this: https://stackoverflow.com/a/69473649 -- then all should be well.

**Comment by byronigoe** [comment] 2022-03-16 17:28
I have both SDK 30 and 29 installed. My config.xml has `<preference name="android-targetSdkVersion" value="30" />` and when I run `cordova platform add android` I get:
```
Using cordova-fetch for cordova-android@^10.1.1
Adding android project...
android-targetSdkVersion should be greater than or equal to 30.
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.gunksapps.gunks
        Name: Gunks
        Activity: MainActivity
        Android target: android-30
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.1
```

Note that it says `android-targetSdkVersion should be greater than or equal to 30.` as though it isn't, but it is. Also, the AndroidManifest (and other generated files) show 29 instead of 30.

As you can see I'm using cordova-android 10.1.1. I'm at a loss.

**Comment by discovermoi** [comment] 2022-05-19 06:23
> I was able finally to build it using `before_build` hook https://github.com/capellasolutions/ionic-cordova-docker/tree/develop/example-app/scripts
> 
> Until this issue is resolved here, maybe in cordova-android 10 or 9.something

Hi, Unable to access the link..

**Comment by almothafar** [comment] 2022-05-19 20:58
> > I was able finally to build it using `before_build` hook https://github.com/capellasolutions/ionic-cordova-docker/tree/develop/example-app/scripts
> > Until this issue is resolved here, maybe in cordova-android 10 or 9.something
> 
> Hi, Unable to access the link..

I removed it when this issue was resolved you can see the commit here https://github.com/capellasolutions/ionic-cordova-docker/commit/626ff047863bfc1b1b15ee0cc025f010d98e0ce8

This is the repo, master branch works, develop is not working right now: https://github.com/capellasolutions/ionic-cordova-docker
