### ISSUE TITLE
HTML 5 Video seekbar not working when exporting apk to cordova.

### ISSUE THREAD

**Issue by Ernesto-Lorenzo12** [apache/cordova-android#1592] opened 2023-04-12 02:34 UTC
# Bug Report

## Problem
Dragging video timeline not working, including fast forward and backward
### What is expected to happen?
Can skip time skip

### What does actually happen?
Seekbar not working when testing out on Android emulator and an actual device.

### Command or Code

I'm using a simple html5 video tag code:

`          <video controls poster="assets/images/history_event_img/event_1.png">
            <source src="assets/videos/dummy_video.mp4" type="video/mp4" id="dummy_video">
          </video>`

### Environment, Platform, Device

I'm using Android Emulator: Pixel XL API 32

### Version information

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2024-02-15 04:33
Duplicate of https://github.com/apache/cordova-android/issues/1494

**Closed by breautek** 2024-02-15 04:33 UTC
