### ISSUE TITLE
android build failed

### ISSUE THREAD

**Issue by ipehimanshu** [apache/cordova-android#1345] opened 2021-09-11 14:50 UTC
Hello 

here is my info

onic CLI                     : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 9.0.6
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0
Cordova:
   Cordova CLI       : 10.0.0
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 19 other plugins)
Utility:
   cordova-res (update available: 0.15.3) : 0.15.1
   native-run (update available: 1.4.1)   : 0.2.8
System:
   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v14.16.1 (/usr/local/bin/node)
   npm        : 6.14.12
   OS         : macOS Big Sur
   Xcode      : Xcode 12.0.1 Build version 12A7300
   
   and it failed with error like
   
   Execution failed for task ‘:app:processReleaseResources’.
> Android resource linking failed
  /Users/herobarua/.gradle/caches/transforms-1/files-1.1/material-1.5.0-alpha03.aar/e6292420a3a6236f6582280b0a94fbc4/res/values-v31/values-v31.xml:3:5-94: AAPT: error: resource android:color/system_neutral1_1000 not found.
  
  So can you please help us what is going wrong, FYI we are not using any material design into our package and we are trying to remove gradle cache also yet same error
  
 Thanks

**Comment by breautek** [comment] 2021-09-11 15:14
What build tools version are you using? Materials is something being added in the android 12 beta I believe.

Assuming you're using cordova-android@10.x, the recommended build tools version is 30.0.3.

**Comment by ipehimanshu** [comment] 2021-09-11 15:18
Cordova Platforms : android 8.1.0

**Comment by breautek** [comment] 2021-09-11 19:38
> Cordova Platforms : android 8.1.0

I still need to know what build tools version you're using. For 8.x, the recommended version would be build tools 28.x.

The build tools should be in your `PATH` variable. Using the terminal command `which aapt` should print you a path that looks like:

```bash
which aapt
/home/norman/Android/Sdk/build-tools/30.0.3//aapt
```

The above example shows that my build-tools version being used is `30.0.3`.

**Comment by dpogue** [comment] 2021-09-11 20:41
One of your plugins is pulling in Google's Material design library `material-1.5.0-alpha03`. This alpha03 version is *only* compatible with Android SDK 31, but Cordova Android 10.x uses SDK 30.

**Comment by breautek** [comment] 2022-05-17 18:55
Closing as not a bug.

**Closed by breautek** 2022-05-17 18:55 UTC
