### ISSUE TITLE
Release version still have debugging enabled

### ISSUE THREAD

**Issue by jrsarath** [apache/cordova-android#500] opened 2018-09-17 22:02 UTC
Hello there,
I'm building a Android app, specified all required fields on build.json upon running 
"Cordova build Android --release --buildConfig"
It does generates app-release.apk which is actually signed by the keystore provided in build.json but when deploying that app on device/emulator chrome://inspect still able to detect and inspect Cordova app.

**Comment by janpio** [comment] 2018-09-18 07:06
That is exactly what is supposed to happen, you should be able to detect and inspect the Cordova app. What exactly is the problem?

**Comment by janpio** [comment] 2018-09-18 07:34
Oh sorry, I misread. That is indeed strange.

**Comment by PIPERAPACHE** [comment] 2018-10-13 20:33
Rec'vg no prob.

**Comment by Menardi** [comment] 2018-12-16 11:54
I'm wondering if there might have been a change in the Android emulators. I have old APKs which I know were not inspectable before, but now can be inspected if they are run on an emulator. However, they are still not inspectable on device.

I have checked the part of the cordova-android code which enables the debugging (https://github.com/apache/cordova-android/blob/5f44af375754f1fa8fddd53834cdf36f4be29a62/framework/src/org/apache/cordova/engine/SystemWebViewEngine.java#L177), and it is not triggered in a release APK. But that APK is still inspectable on an emulator. So, I feel it must be a change in the emulators that forces everything to be inspectable.

**Comment by breautek** [comment] 2020-04-13 01:17
Cannot reproduce this using the latest cordova tooling.

Closing because this may be out-dated. If the issue persists, feel free to open a new issue and include all the information requested in the form, thanks.

**Closed by breautek** 2020-04-13 01:17 UTC
Labels: support
