### ISSUE TITLE
When is Android X support coming?

### ISSUE THREAD

**Issue by semerda** [apache/cordova-android#840] opened 2019-10-10 20:16 UTC
When is Android X support coming?

**Comment by brodybits** [comment] 2019-10-10 21:14
Unfortunately we cannot make any promises due to lack of resources, see apache/cordova#163

**Comment by breautek** [comment] 2019-10-13 00:42
In the meantime, as a workaround there are 2 plugins available to enable androidx

https://github.com/dpa99c/cordova-plugin-androidx
https://github.com/dpa99c/cordova-plugin-androidx-adapter

**Comment by jcesarmobile** [comment] 2019-10-20 22:26
closing as duplicate of https://github.com/apache/cordova-android/issues/565

**Closed by jcesarmobile** 2019-10-20 22:26 UTC
