### ISSUE TITLE
Can't set preference for compileSdkVersion/buildToolsVersion

### ISSUE THREAD

**Issue by Sujay-shetty** [apache/cordova-android#1281] opened 2021-07-15 12:15 UTC
Hi,

I'm new to cordova-android development and trying to build application.

while building application if I specify preference in config.xml for updating the properties it is not reflecting in build apk manifest file. Below are the preferences I'm updating.

`<preference name="android-compileSdkVersion" value="30" />
<preference name="android-buildToolsVersion" value="30.0.0" />`

cordova-android version - 9.1.0
cordova version - 10.0.0

could you please help me in how to set above two properties for building apk.

**Comment by breautek** [comment] 2021-07-15 13:42
`android-compileSdkVersion` or `android-buildToolsVersion` are not preferences on cordova-android@9. You can view a list of preferences [here](https://cordova.apache.org/docs/en/10.x/config_ref/index.html).

Cordova does expose compile and sdk tools options via gradle. See https://cordova.apache.org/docs/en/10.x/guide/platforms/android/index.html#setting-gradle-properties for how to use gradle options.

Note that these are being cleaned up in our next major release that is pending. `cdvCompileSdkVersion` is being removed, and the existing `android-targetSdkVersion` config preference will now set both target and compile sdk. I think [android-buildToolsVersion](https://github.com/apache/cordova-android/blob/master/lib/prepare.js#L96) is also being added as a config preference in `cordova-android@10`

I'm closing this issue becaues it's not a bug. If you require further support, I recommend asking our [Slack community](http://slack.cordova.io/).

Kind Regards,

**Closed by breautek** 2021-07-15 13:42 UTC
