### ISSUE TITLE
After updating android studio: Cordova app module isn't auto recognized anymore

### ISSUE THREAD

**Issue by BorntraegerMarc** [apache/cordova-android#653] opened 2019-02-08 07:49 UTC
After updating android studio to:
```
Android Studio 3.3.1
Build #AI-182.5107.16.33.5264788, built on January 29, 2019
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2
```

I get the following error when building my cordova app for android:
![screenshot 2019-02-08 at 08 46 55](https://user-images.githubusercontent.com/7549295/52465251-382f2c00-2b7e-11e9-8fba-c9541b731cf0.png)

I need to manually click `File -> Sync Project with Gradle Files` for the module to be recognized. This was not the case with my last version of Android studio (v3.2.1)

**Comment by brodybits** [comment] 2019-02-10 04:18
Please try with cordova-android@nightly. Recent change may resolve the issue for you.

**Comment by BorntraegerMarc** [comment] 2019-02-10 11:56
Hi @brodybits 
I couldn't really test it with nightly since I couldn't solve the error I get when building: `Minimum supported Gradle version is 4.10.1. Current version is 4.4. If using the gradle wrapper, try editing the distributionUrl in /Users/borntsch/Documents/komed/komed-frontend/gradle/wrapper/gradle-wrapper.properties to gradle-4.10.1-all.zip`

But I guess I can verify whether the bug is fixed in the next release...

**Comment by erisu** [comment] 2021-07-30 07:23
I am closing out this ticket as I am unable to reproduce this issue.

Since the original ticket creation, there has been numerous releases. I would recommend upgrading your tooling (Android Studio & Gradle, Cordova CLI) and the Cordova-Android platform for your project.

If this issue still exists or ever appears again, please create a new ticket with updated infromation including steps for reproduction. Make sure to also be use the latest tooling & platform.

**Closed by erisu** 2021-07-30 07:23 UTC
Labels: support
