### ISSUE TITLE
Screen Flickering black when two or more video tags come in ionic 4 Android

### ISSUE THREAD

**Issue by haseebazeem15** [apache/cordova-android#1035] opened 2020-07-28 02:41 UTC
# Bug Report
I have feed app, where i am showing images as well as videos. When video comes on scroll, i am facing black screen. :(
## Problem
Screen Flickering Black everytime when two or more videos come in Android.

Using ionic 4 cordova cli

![WhatsApp Image 2020-07-28 at 7 47 11 AM](https://user-images.githubusercontent.com/39488408/88613368-ba7b1b00-d0a6-11ea-8d4d-7843432d4462.jpeg)

**Comment by timbru31** [comment] 2020-07-28 08:47
Duplicate of #1031

**Closed by timbru31** 2020-07-28 08:47 UTC
