### ISSUE TITLE
Couldn't clean, run and build existing Cordova 8 projects which was working? 

### ISSUE THREAD

**Issue by enfield09** [apache/cordova-android#1630] opened 2023-07-05 05:55 UTC
# Bug Report

## Problem
I able to build the existing or new projects.

### What does actually happen?
this is what we get, when trying to build or clean, or run, 

[build issue. txt] (https://github.com/apache/cordova-android/files/11954215/build.issue.txt)
attached a file.

either not able to build a new sample project created

## Information
we are using cordova 8, JDK 8.1, gradle version 6.5.
we have tried re install everything fresh even though did not work. 
some devices could not build all the projects we have,
 in some other devices we couldn't build only some of the projects,
but all the projects have the same configuration.

**Comment by breautek** [comment] 2023-07-05 11:16
Until cordova-android@10, cordova-android used jcenter repository which they have long decided to shut down. Others have raised a [discussion](https://github.com/apache/cordova/discussions/414) because while they promised to maintain a read-only copy of jcenter, they recently decided to shut down their repository and instead just mirror maven central, which may not have all the packages, or the desired versions of those packages. Your issue sounds like it's caused by this.

Closing because cordova-android 8 is not a supported platform. It does not support the target SDK that Google Play requires. Therefore I'd recommend allocating time upgrading to cordova-android@12, which is our current release.

If you require cordova-android@8 for some reason, then you'll probably need to build up your own local maven repository, find a way to source all the required dependencies and modify the cordova framework to use your local maven repository.

**Closed by breautek** 2023-07-05 11:16 UTC
