### ISSUE TITLE
Missing Intent type and category prevent file upload - [solution included]

### ISSUE THREAD

**Issue by gabriele-sacchi** [apache/cordova-android#695] opened 2019-03-21 03:49 UTC
# Bug Report
Files upload not working on Android when the Cordova App uses [ng-file-upload](https://github.com/danialfarid/ng-file-upload/issues/2111).

( works on iOS 👇👇  )
![image](https://user-images.githubusercontent.com/48427520/54739187-9c85d800-4b8d-11e9-8750-76cd378ec145.png)

## Problem
Using [ng-file-upload](https://github.com/danialfarid/ng-file-upload) it is not possible to upload images or document on Android when the App is built using Cordova.

The 2 lines fix suggested below will resolve the Issue opened [here](https://github.com/danialfarid/ng-file-upload/issues/2111) on the ng-file-upload repository and the [related Stackoverflow](https://stackoverflow.com/questions/55261705/file-upload-not-working-for-android-in-cordova-project).

This is the line after which the following 2 lines of code need to be added:
https://github.com/apache/cordova-android/blob/2163c8ae0536bfde9029cfc981b945f4af93e09f/framework/src/org/apache/cordova/engine/SystemWebChromeClient.java#L253

Bug fix - **2 lines of code**:
```
    @TargetApi(Build.VERSION_CODES.LOLLIPOP)
    @Override
    public boolean onShowFileChooser(WebView webView, final ValueCallback<Uri[]> filePathsCallback, final WebChromeClient.FileChooserParams fileChooserParams) {
        Intent intent = fileChooserParams.createIntent();
        // FIX HERE (same as the above handler) vvvvvvvvvvvvvv @@
        intent.addCategory(Intent.CATEGORY_OPENABLE); 
        intent.setType("*/*");
        // FIX HERE ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ @@
```

### What is expected to happen?
The user should be prompted to choose which app to use to pick a file to upload

### What does actually happen?
On click no file picker is shown

## Information
These logs get generated when the upload button that should open the file picker is clicked:

"No activity found to handle file chooser intent.: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.GET_CONTENT cat= [android.intent.category.OPENABLE] typ=.jpg,.png,.tiff,.jpeg,.tif,.pdf }"

### Command or Code
Unfortunately I cannot share the code.

### Environment, Platform, Device
Android app built with Cordova.

Same result using the default WebView and the WebView provided by cordova-plugin-ionic-webview.

### Version information
Same result on cordova-android 7 and 8.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by gabriele-sacchi** [comment] 2019-03-21 04:01
Could I please ask how long it will take to have a release including this bug fix? We rely on this plugin and need to go live in about a month. Thanks 🙏

**Comment by janpio** [comment] 2019-03-22 10:30
Feel free to create a Pull Request with your suggested changes so it can be reviewed and possibly merged.

**Comment by MatusFiala** [comment] 2019-03-22 11:55
@gabriele-sacchi thank you, but your code will have some problems. Your params should be set in the calling webapp and not in SystemWebChromeClient. Especially "intent.setType("*/*")" will create an intent for all types. So if you just want a filepicker for pictures, you would get a picker where you could select all types like videos, pdfs, etc. 
So either the calling app has to fix it, to only load the given file-type, or the user may have a really bad user-experience.

Normally these params are written in the "WebChromeClient.FileChooserParams" of onShowFileChooser(). So you're at the rigth method. You just have to read out the WebChromeClient.FileChooserParams-Object and pass the params to the intent.

**Comment by gabriele-sacchi** [comment] 2019-04-01 03:34
I opened this stackoverflow: https://stackoverflow.com/questions/55447711/convert-mime-types-in-filechooserparams-to-the-right-format-for-intent-settype

It seems like the intent category and intent type are already set because they are extracted from WebChromeClient.FileChooserParams object when the intent is created. I suspect though that the mime types are set incorrectly. This is the error in the terminal:
`No activity found to handle file chooser intent.: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=.jpg,.png,.tiff,.jpeg,.tif,.pdf }`.

If I use `intent.setType("image/* application/pdf");` everything works fine but I'm not sure whether hardcoding these values in this repo would be a good solution. At the same time I believe that this cannot be changed in ng-file-upload either (and I dont seem to find these values in their repo).

Thoughts?

**Comment by gabriele-sacchi** [comment] 2019-04-01 04:21
I simply added the following 2 lines in my PR:
```
intent.setType("image/*");
intent.putExtra(Intent.EXTRA_MIME_TYPES, fileChooserParams.getAcceptTypes());
```
**Outcome:**
```
2019-04-01 00:18:00.501 32500-32500/my.app.bundle.id D/SystemWebChromeClient: : fileChooserParams.getAcceptTypes(): [.jpg,.png,.tiff,.jpeg,.tif,.pdf]
2019-04-01 00:18:00.503 2225-2921/system_process I/ActivityManager: START u0 {act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=image/* cmp=com.android.documentsui/.picker.PickActivity (has extras)} from uid 10105
```

**Comment by gabriele-sacchi** [comment] 2019-04-01 04:25
@MatusFiala regarding your comment about `intent.setType("*/*")` please note that its sibling [openFileChooser](https://github.com/apache/cordova-android/blob/2163c8ae0536bfde9029cfc981b945f4af93e09f/framework/src/org/apache/cordova/engine/SystemWebChromeClient.java#L239) uses `intent.setType("*/*")`.

```
    public void openFileChooser(final ValueCallback<Uri> uploadMsg, String acceptType, String capture)
    {
        Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType("*/*");
```

**Comment by gabriele-sacchi** [comment] 2019-04-01 07:15
PR awaiting approval. I did not have a chance to add unit tests though.. :(

**Comment by drastik** [comment] 2019-04-05 18:19
I can confirm same issue, building with Quasar Framework, cordova 9, `cordova-android 8.0.0`
  
`/com.ourAppName.app D/SystemWebChromeClient: Receive file chooser URL: null`  

No prompts to choose file source, opens a default.  Can't upload certain media types.

**Comment by breautek** [comment] 2020-05-15 00:51
Is there way to reproduce this with no frameworks?

I've simply added a `<input type="file" />` tag in the basic cordova hello world app, and I get a fully featured file picker/browser.

Also, what android versions was this observed on?

**Comment by ksch10bob** [comment] 2020-06-12 13:27
@breautek 
i can only speak for android Versions from 5.xx 

case 1 : no or an empty accept attribute is specified. Works like intended, you get the fully featured file picker

case 2 : your specify an accept attribute on the input tag that contains at least 2 entries
try ```<input type="file"   accept="application/pdf, image/jpeg"   />``` in your minimal cordova repo

## expected
you can choose jpegs and pdfs

## actually

you can only choose pdfs

**Comment by breautek** [comment] 2020-06-13 01:47
Thank you @ksch10bob I've confirmed the issue using your information.

I tried the following:
* `<input type="file" accept="application/pdf, image/jpeg" />`
* `<input type="file" accept="application/pdf, image/jpg" />`
* `<input type="file" accept="image/jpeg" />`
* `<input type="file" accept="image/*" />`

Each of these cases I've observed that jpg were not selectable, when they were expected to be.

I've also pulled down the PR #971 (not sure if it implements the same solution provided in this issue) and confirmed that the PR does address the problem :+1:

**Comment by Michael-Shemesh** [comment] 2020-06-14 04:49
Did you also check with this?
* `<input type="file" accept="*/*" />`
* `<input type="file" accept="*" />`

I found that there are differenced in iOS and Android, each accepts one of these, but there is no way to allow all files on both iOS and Android...

**Comment by breautek** [comment] 2020-06-14 13:08
I didn't try that specifically but for android omitting the `accept` attribute had the effect of allowing any file.

**Comment by Michael-Shemesh** [comment] 2020-06-15 05:29
Many thanks!

**Closed** 2020-06-18 12:59 UTC
