### ISSUE TITLE
ionic cordova platform add - fails to update build.gradle with proper android gradle plugin

### ISSUE THREAD

**Issue by nhhockeyplayer** [apache/cordova-android#947] opened 2020-04-09 09:43 UTC
# Bug Report
ionic cordova platform add - fails to update build.gradle with proper android gradle plugin

## Problem
causes build to fail

### What is expected to happen?
when adding a new plaform, build.gradle should reflect the appropriate android gradle plugin not some hardwired guess like 3.3.0

### What does actually happen?
version 3.3.0 is what lands inside the platforms/android/build.gradle instead of 3.6.2 which syncs the gradle version with the version of android studio I am using which is in fact 3.6.2

## Information
android studio 3.6.2
gradle version 3.6.4

this is the problem causing builds to fail
android gradle plugin version 3.3.0 (suppose to be 3.6.2 in sync with android studio)

**Comment by raphinesse** [comment] 2020-04-10 11:41
> forking to fix is another unacceptable avenue
> its too much work

It was proposed as a workaround. Take it or leave it.

> why cant it just work

The age-old question

---

I'm not so proficient with the android build, but can the gradle plugin version be overridden with [build-extras.gradle](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#extending-buildgradle)?

**Comment by nhhockeyplayer** [comment] 2020-04-10 15:26
My standards are of the highest premium
I come form the X-Wiindows days at DEC when MIT released a solid product to the public domain that was bullet proof and was used commercially in manufacturing everywhere including Johnson & Johnson Orthopaedics.

I have little respect for google proof is in the pudding and they could have only nabbed javascript and outperformed their rivals in Switzerland by dong it all as open source. But they couldnt even do that Microsoft had to bail them out with typescript and done it the right way made in usa and still doing what american innovation is SUPPOSE to  be doing.

WORKAROUND (to avoid the multidimensional train-wreck of hardwired dependencies at all flanks)
uninstall android stdio and back that down to version 3.3.0 and no need to desecrate the archetypes

**Comment by breautek** [comment] 2020-04-10 18:52
I'm still able to build successfully with a simple android app with android studio 3.6.2, with the gradle plugin 3.3.0.

Which means there is another variable at play that is currently unknown. If you can provide a [minimum reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) that may help us identify the exact cause.

Do note that in my tests I'm not using ionic. If the problem only presents itself with ionic, then going through ionic's channels will be more appropriate.

**Comment by rolinger** [comment] 2020-04-18 02:30
I have never imported my project into Android Studio until today.  I needed the Image Asset tool to help create proper round icons need for various devices.  When I imported my project it said I need to update my gradle to 5.1.1 - so I did.

After I created all my icons and updated my cordova projects config.xml file with the necessary resource-file configs - I then compile my project from command line again and now I get a gradle error:

```
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.10.3. If using the gradle wrapper, try editing the distributionUrl in c:\Users\RPO\dev\myApp\gradle\wrapper\gradle-wrappe
r.properties to gradle-5.1.1-all.zip
```

The problem is, that path doesn't exist in my root project folder - there is no `/gradle/` folder in my project root.  There is a `.gradle` folder in my root /users directory - but I can't find a `gradle-wrapper.properties` file anywhere.

**Comment by breautek** [comment] 2020-04-18 02:44
@rolinger You can try using `cordova-android@nightly` as a test to see if it solves your problem. 9.0 (unreleased, no release eta) is refactored to support gradle 5.x+ (it actually uses 6.1...).

Additionally an unrelated PR was recently landed in master that bumps the gradle plugin to 3.5.3 (although not to the latest 3.6.0...) which may have solved this issue as well.

**Comment by rolinger** [comment] 2020-04-18 02:48
@breautek  - so my install is Cordova@9, and Cordova-Android@8.1 - what gradle version should my project be on?  All was fine running 4.10.3 until I needed that damn Android Studio Image Asset tool.  Now that I have all the icons it might just be better if I use 4.10.3, however because cli compile fails saying it needs 5.1.1 - how can I change the regular project to go back to using 4.10.3?

I fear trying to force my project to 5.1.1 is just going to open a can of worms I won't be able to fix.

**Comment by breautek** [comment] 2020-04-18 02:59
Untested, but if you open up `platforms/android/app/build.gradle`

You should have..

```
buildscript {
    repositories {
        mavenCentral()
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}
```

Probably around line 52. `com.android.tools.build:gradle` should be pinned to `3.3.0`

Additionally, at around line 74, you should have:

```
task wrapper(type: Wrapper) {
    gradleVersion = '4.10.3'
}
```

Do note that you're line numbers will be slightly different cause I'm referencing a custom cordova-android build.

If you open the android project in android studio, one of the things it will do is detect that you're using an old `com.android.tools.build:gradle` (the Android Gradle Plugin), and prompt you to upgrade it, so this is likely what you were seeing. `cordova-android@8.x` expects this plugin to be set to version `3.3.0`.

If you need further assistance, I would invite you to our [slack](http://slack.cordova.io/) so we can stop hijacking this thread, thanks.

**Comment by rolinger** [comment] 2020-04-18 03:03
@breautek  - thanks.  Going to try fixing this and if not success will move to slack.

**Comment by breautek** [comment] 2020-05-22 03:11
Closing this as https://github.com/apache/cordova-android/pull/962 is merged in, and apparently solves this issue.

**Closed by breautek** 2020-05-22 03:11 UTC
Labels: info-needed
