### ISSUE TITLE
Issue to copy library from plugin after updating to v7.1.2

### ISSUE THREAD

**Issue by afdev82** [apache/cordova-android#540] opened 2018-11-09 12:46 UTC
Everything worked fine in v7.1.1

Now after updating to v7.1.2 I get this error:
```
BUILD FAILED in 7s
3 actionable tasks: 3 executed
/home/antonio/Projects/smartMirror/smartMirrorApk/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find :deezer-sdk_library-release:.
  Searched in the following locations:
      file:/home/antonio/Projects/smartMirror/smartMirrorApk/platforms/android/app/libs/deezer-sdk_library-release.aar
  Required by:
      project :app
```

This is the line in my `plugin.xml` for the plugin that needs the library:
```
<source-file src="src/android/libs/deezer-sdk_library-release.aar" target-dir="app/libs/" />
```

I think this could be related to this change: https://github.com/apache/cordova-android/compare/7.1.1...7.1.2#diff-4f73e5f70cec312ae82aa7d023e3c88b

**Comment by brodybits** [comment] 2018-11-09 13:32
>
>  This is the line in my plugin.xml for the plugin that needs the library:
>
> <source-file src="src/android/libs/deezer-sdk_library-release.aar" target-dir="app/libs/" />
>
> I think this could be related to this change: 7.1.1...7.1.2
> diff-4f73e5f70cec312ae82aa7d023e3c88b
> <https://github.com/apache/cordova-android/compare/7.1.1...7.1.2diff-4f73e5f70cec312ae82aa7d023e3c88b>
>

Link does not work for me.

Can you confirm if you have a test case that shows the functionality
working on 7.1.1 but not on 7.1.2? What about the master branch?

I see you did raise a PR on 7.1.x (<
https://github.com/apache/cordova-android/pull/539>). We would likely need
the same change on master if it is accepted on 7.1.x.

>

**Comment by brodybits** [comment] 2018-11-09 13:35
>
> I see you did raise a PR on 7.1.x (<
> https://github.com/apache/cordova-android/pull/539>). We would likely need
> the same change on master if it is accepted on 7.1.x.
>


Sorry it was someone else who raise a proposed fix in <
https://github.com/apache/cordova-android/pull/539>.

>

**Comment by afdev82** [comment] 2018-11-09 14:07
For the link: https://github.com/apache/cordova-android/commit/ea6477f4d3e63ebb1f1717cc02e3117aa356ce84#diff-4f73e5f70cec312ae82aa7d023e3c88b

For the test case... I just execute `cordova platform add android` and I see that the `platforms/android/app/libs` gets not created with the new version.

I didn't try with the master branch, how could I target this?

PS: I also noticed that if I run `cordova prepare android` this command updates the cordova-android version, but as far as I know it's not supposed to do that (I think this is a problem with cordova anyway)

**Comment by brodybits** [comment] 2018-11-09 15:04
> For the test case... I just execute `cordova platform add android` and I see that the `platforms/android/app/libs` gets not created with the new version.

Can you tell which plugin triggers this behavior?

> I didn't try with the master branch, how could I target this?

A couple options:

* do `cordova platform add https://github.com/apache/cordova-android#master` (added `#master` to the end to be on the safe side)
* do `cordova platform add android@nightly`



> I also noticed that if I run `cordova prepare android` this command updates the cordova-android version, but as far as I know it's not supposed to do that (I think this is a problem with cordova anyway)

Please report this in a separate issue, along with clear reproduction steps

**Comment by brodybits** [comment] 2018-11-09 16:54
I just reproduced this issue in a unit test in WIP PR #541. It is caused by the following change in commit ea6477f4d3e63ebb1f1717cc02e3117aa356ce84:
* [CB-13830](https://issues.apache.org/jira/browse/CB-13830): Add handlers for plugins that use non-Java source files, such as Camera

**Comment by brodybits** [comment] 2018-11-09 19:33
@afdev82 it would really help us if you can name the specific plugin that triggers this issue.

We will need to make a specific exception to solve this issue without breaking old plugin compatibility.

**Comment by j3k0** [comment] 2018-11-12 06:18
Hi @brodybits 
The `cc.fovea.cordova.purchase` plugin has the same error (fails on 7.1.2, succeeds on 7.1.1). Cf https://github.com/j3k0/cordova-plugin-purchase/issues/756

**Comment by afdev82** [comment] 2018-11-12 08:11
> @afdev82 it would really help us if you can name the specific plugin that triggers this issue.
> 
> We will need to make a specific exception to solve this issue without breaking old plugin compatibility.

Hi, the plugin is this: https://github.com/adnotam/cordova-plugin-deezer

**Comment by brodybits** [comment] 2018-11-12 16:20
Thanks guys. We will test installation with both plugins before releasing the next patch. I think we will need another unit test to check installation of `.aidl` for cordova-plugin-purchase.

**Comment by brodybits** [comment] 2018-11-12 16:35
> Yes, we had to put an [ugly hack](https://github.com/j3k0/cordova-plugin-purchase/blob/master/scripts/androidBeforeInstall.js#L21-L25) in place to have installation/uninstallation work in all cases.

Starting with <https://github.com/j3k0/cordova-plugin-purchase/commit/cc229abea3e27330a780d77a335d3b5037824b4d>

Which seems to deal with the changed `res` location. I wish you had reported it to us. We did make some efforts to support plugins using the old project structure in the recent patch release, think it would be ideal if we could do this as well.

**Comment by j3k0** [comment] 2018-11-12 16:46
> I wish you had reported it to us

I didn't as I as thought I was doing something wrong and ended up finding workarounds.

I have no problems reporting all sorts of installation issues we encounter if it's helpful to you... and if it's ok when I end up being the one that screwed up.

Looking forward for the fix!

**Comment by brodybits** [comment] 2018-11-12 17:04
@j3k0 I just raised #546 for tracking of the issues with cordova-plugin-purchase.

**Comment by afdev82** [comment] 2018-11-13 10:29
> > I think we will need another unit test to check installation of `.aidl` for cordova-plugin-purchase.
> 
> Yes, we had to put an [ugly hack](https://github.com/j3k0/cordova-plugin-purchase/blob/master/scripts/androidBeforeInstall.js#L21-L25) in place to have installation/uninstallation work in all cases.

Yes, I have also problems to uninstall the plugin too... It doesn't remove the library and if I try to readd the plugin again it throws an error because the library is still there.

**Comment by brodybits** [comment] 2018-11-13 17:49
Issues with `cordova-plugin-deezer` and <https://github.com/j3k0/cordova-plugin-purchase> should now be solved by PR #542 on `master` branch, will be ported to upcoming 7.1.3 patch release.

@j3k0 I am working on a solution that will support `https://github.com/j3k0/cordova-plugin-purchase#v7.1.0` (before you made adaptations for cordova-android@7) as part of #547.

**Comment by jcesarmobile** [comment] 2018-11-13 22:34
Closing as the PR was merged in master

**Closed by jcesarmobile** 2018-11-13 22:34 UTC
Labels: bug

**Comment by brodybits** [comment] 2018-11-21 23:53
Now fixed in the latest patch release
