### ISSUE TITLE
excludeFromRecents="true" causes app to be killed on Android 9

### ISSUE THREAD

**Issue by 8bhsolutions** [apache/cordova-android#851] opened 2019-10-18 13:37 UTC
# Bug Report
On Android 9 (sdk 28), when app has the android:excludeFromRecents="true" for the activity, when you opened YouTube (or other apps), the cordova app is killed.

## Problem
The app is terminated. No error is shown in logcat

### What is expected to happen?
The app should not be impacted

### What does actually happen?
The app process is killed

## Information
After cloning the repo (provided below), run the following commands on the root directory to generate an android apk

```
npm install
ionic cordova build android
```
Then deploy apk on device to test

**Steps**

1. Start the app. (NOTE - The start date on the Home Tab shows when the instance of the app is started. It will remain static for the duration of the app instance.)
2. Once app is started. Go to app launcher
3. Launch Calculator app (or another app)
4. Go back to the app - via app launcher (since the app is excluded from recent list). 
5. Notice the app starts a new instance (because app start date is different).

-----

No errors/exceptions in logcat for why the CordovaActivity is killed (line 2 below)

```
10-19 00:42:00.380: W/libprocessgroup(486): kill(-2215, 9) failed: No such process
10-19 00:42:00.388: D/CordovaActivity(2560): CordovaActivity.onDestroy()
10-19 00:42:00.391: D/CordovaWebViewImpl(2560): >>> loadUrl(about:blank)
10-19 00:42:00.392: W/cr_AwContents(2560): WebView.destroy() called while WebView is still attached to window.
10-19 00:42:00.399: W/Finsky(1820): [2] com.google.android.finsky.analytics.az.a(40): Null bundle, which breaks event chain!. Creating a new logging context.
10-19 00:42:00.406: I/Zygote(317): Process 1516 exited due to signal (9)
10-19 00:42:00.417: I/Zygote(317): Process 2215 exited due to signal (9)
10-19 00:42:00.424: W/libprocessgroup(486): kill(-2215, 9) failed: No such process
10-19 00:42:00.424: I/libprocessgroup(486): Successfully killed process cgroup uid 10071 pid 2215 in 44ms
10-19 00:42:00.424: W/libprocessgroup(486): kill(-1516, 9) failed: No such process
10-19 00:42:00.424: I/libprocessgroup(486): Successfully killed process cgroup uid 10023 pid 1516 in 0ms
10-19 00:42:00.439: I/ActivityManager(486): START u0 {act=android.intent.action.MAIN cmp=com.android.vending/com.google.android.finsky.unauthenticated.UnauthenticatedMainActivity (has extras)} from uid 10079
10-19 00:42:00.486: E/chromium(2560): [ERROR:gl_context_virtual.cc(39)] Trying to make virtual context current without decoder.
10-19 00:42:00.546: W/cr_AwContents(2560): Application attempted to call on a destroyed WebView
10-19 00:42:00.546: W/cr_AwContents(2560): java.lang.Throwable
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.android_webview.AwContents.isDestroyed(AwContents.java:351)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.android_webview.AwContents.isDestroyedOrNoOperation(AwContents.java:323)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.android_webview.AwContents.getTitle(AwContents.java:585)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.android_webview.AwWebContentsDelegateAdapter.loadingStateChanged(AwWebContentsDelegateAdapter.java:132)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at android.os.Looper.loop(Looper.java:193)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at android.app.ActivityThread.main(ActivityThread.java:6680)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at java.lang.reflect.Method.invoke(Native Method)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-19 00:42:00.546: W/cr_AwContents(2560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-19 00:42:00.564: W/SurfaceFlinger(370): Attempting to destroy on removed layer: AppWindowToken{5fd14b3 token=Token{aac2222 ActivityRecord{c4853ed u0 io.ionic.starter/.MainActivity t48}}}#0
10-19 00:42:00.603: I/cr_ChildProcessService(2724): Destroying ChildProcessService pid=2724
10-19 00:42:00.605: I/ActivityManager(486): Killing 2724:com.android.webview:sandboxed_process1/u0a4i1 (adj 0): isolated not needed

```

-----

The bug is more obvious if you include https://github.com/katzer/cordova-plugin-background-mode plugin to the source, because the foreground notification associated with the app is removed when the app is killed.

I purposely choose to not include the background mode plugin in the sample project to isolate the issue.

### Command or Code
I have created a blank Ionic (cordova based) project to demonstrate the bug/

https://github.com/8bhsolutions/test-excludeFromRecents

### Environment, Platform, Device
Android 9
Real device - Samsung S9+ running latest Android 9
Emulator (Genymotion v3.0.3) - Samsung S9 - Android 9 - stock image

### Version information

Ionic:

   Ionic CLI          : 5.2.3
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 4 other plugins)

Utility:

   cordova-res : 0.8.0
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v10.16.0
   npm               : 6.9.0
   OS                : Windows 10

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2019-10-19 21:39
I'm unable to reproduce this with a plain cordova app on an API 29 or API 28 emulator. 

I tested this by creating a new app and install the `splashscreen` plugin so that I can delay the splashscreen to make it obvious whether the splashscreen was being launched. Using `excludeFromRecents` worked properly with the app not being displayed in the recents app list, and opening up other apps did not cause the splashscreen to appear again. The only way I could make the splashscreen appear is by force exiting the app.

I can however reproduce it using your test app. This suggests that the problem is in the ionic codebase, not Cordova's. Therefore I'll be closing this issue.

I'd advise raising an issue with the ionic team with your sample app as you posted here. If you do find something wrong in the cordova codebase, or if ionic's investigation leads back into Cordova then please don't hesitate to open a new issue with us.

**Closed by breautek** 2019-10-19 21:39 UTC

**Comment by brucejo75** [comment] 2019-11-25 16:55
@breautek, @8bhsolutions,

I also started seeing this throw on Android 9 with Cordova 7.1.4.

I am wondering if chromium issue  [#511243](https://bugs.chromium.org/p/chromium/issues/detail?id=511243&q=WebView.destroy&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) provides a clue to what is happening.

Here is my log snippet:
```
=== MyApp receives an onDestroy()
11-25 07:16:39.127  4294  4294 D MyApp   : H:C:SE:E in onDestroy()
11-25 07:16:39.128  4294  4294 D CordovaWebViewImpl: >>> loadUrl(about:blank)

=== Warning message is output
11-25 07:16:39.132  4294  4294 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.

=== Chrome receives the onUnload event and MyApp makes a plugin call that simply logs the event
11-25 07:16:39.136  4294  4542 D MyApp   : H:C:SE:E in jv.execute:test [MyApp1057410358]
11-25 07:16:39.137  4294  4542 D MyApp   : H:C:SE:E myapp.test received: In onUnload
11-25 07:16:39.141  4294  4294 D ViewRootImpl@27672fa[MainActivity]: dispatchDetachedFromWindow
11-25 07:16:39.148  4294  4294 D InputTransport: Input channel destroyed: fd=155

=== After I log it with my plugin I output it in the chrome console
11-25 07:16:39.149  4294  4294 I chromium: [INFO:CONSOLE(4456)] "[07:16:39:134]  WARN: MyApp: In onUnload unload$ (http://localhost:12848/__cordova/app.js?hash=ad91e9f827dd8287d263256b1de4d4e03de05f73:6547:27)  ", source: http://localhost:12848/__cordova/packages/myapp_base.js?hash=deae68068b750d5d115ea91e0aa2a6c6b8e3eaa6 (4456)

=== Receive throw
11-25 07:16:39.151  4294  4294 W cr_AwContents: Application attempted to call on a destroyed WebView
11-25 07:16:39.151  4294  4294 W cr_AwContents: java.lang.Throwable
11-25 07:16:39.151  4294  4294 W cr_AwContents: 	at org.chromium.android_webview.AwContents.a(PG:132)
11-25 07:16:39.151  4294  4294 W cr_AwContents: 	at tD0.loadingStateChanged(PG:2)
11-25 07:16:39.151  4294  4294 W cr_AwContents: 	at android.os.MessageQueue.nativePollOnce(Native Method)
11-25 07:16:39.151  4294  4294 W cr_AwContents: 	at android.os.MessageQueue.next(MessageQueue.java:326)
11-25 07:16:39.151  4294  4294 W cr_AwContents: 	at android.os.Looper.loop(Looper.java:183)
11-25 07:16:39.151  4294  4294 W cr_AwContents: 	at android.app.ActivityThread.main(ActivityThread.java:7266)
11-25 07:16:39.151  4294  4294 W cr_AwContents: 	at java.lang.reflect.Method.invoke(Native Method)
11-25 07:16:39.151  4294  4294 W cr_AwContents: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
11-25 07:16:39.151  4294  4294 W cr_AwContents: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

This makes me think that cordova may be destroying the WebView before chromium has fully handled the destroy?

I think it is a benign error for me because chrome gets tossed from memory at that point and any leaking does not cause a problem for my usage.

I would test this with Cordova 9, but the tool I am using (meteor) is only at `7.1.4`.

**Comment by breautek** [comment] 2019-11-25 17:19
@brucejo75 If you can provide a pure cordova sample app that demonstrates this issue I can reopen it.

But I suspect that `Application attempted to call on a destroyed WebView` is being thrown because you're making a plugin call in an `onunload` event. I'm not 100% sure on this, but I thought only synchronous APIs were safe in the on unload event. Asynchronous APIs (such as plugin calls) won't make the browser/webview wait before it gets destroyed. This needs to be confirmed however.

**Comment by brucejo75** [comment] 2019-11-25 18:10
Thanks @breautek, I was thinking that might be an issue myself.

I removed the asynchronous call to my plugin.  All I do is a console.log and I still get the same throw:

```
=== MyApp receives an onDestroy()
11-25 10:04:07.890  4294  4294 D MyApp   : H:C:SE:E in onDestroy()
11-25 10:04:07.891  4294  4294 D CordovaWebViewImpl: >>> loadUrl(about:blank)

=== Warning message is output
11-25 10:04:07.893  4294  4294 W cr_AwContents: WebView.destroy() called while WebView is still attached to window.
11-25 10:04:07.904  4294  4294 D ViewRootImpl@1b470c[MainActivity]: dispatchDetachedFromWindow
11-25 10:04:07.912  4294  4294 D InputTransport: Input channel destroyed: fd=147

=== Chrome receives the onUnload MyApp logs the event to Chrome console
11-25 10:04:07.913  4294  4294 I chromium: [INFO:CONSOLE(4456)] "[10:04:07:895]  WARN: MyApp: In onUnload unload$ (http://localhost:12848/__cordova/app.js?hash=406696345d4b8196e2b23fddea15d5566329517e:6547:27)  ", source: http://localhost:12848/__cordova/packages/myapp_base.js?hash=deae68068b750d5d115ea91e0aa2a6c6b8e3eaa6 (4456)

=== Receive throw
11-25 10:04:07.915  4294  4294 W cr_AwContents: Application attempted to call on a destroyed WebView
11-25 10:04:07.915  4294  4294 W cr_AwContents: java.lang.Throwable
11-25 10:04:07.915  4294  4294 W cr_AwContents: 	at org.chromium.android_webview.AwContents.a(PG:132)
11-25 10:04:07.915  4294  4294 W cr_AwContents: 	at tD0.loadingStateChanged(PG:2)
11-25 10:04:07.915  4294  4294 W cr_AwContents: 	at android.os.MessageQueue.nativePollOnce(Native Method)
11-25 10:04:07.915  4294  4294 W cr_AwContents: 	at android.os.MessageQueue.next(MessageQueue.java:326)
11-25 10:04:07.915  4294  4294 W cr_AwContents: 	at android.os.Looper.loop(Looper.java:183)
11-25 10:04:07.915  4294  4294 W cr_AwContents: 	at android.app.ActivityThread.main(ActivityThread.java:7266)
11-25 10:04:07.915  4294  4294 W cr_AwContents: 	at java.lang.reflect.Method.invoke(Native Method)
11-25 10:04:07.915  4294  4294 W cr_AwContents: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
11-25 10:04:07.915  4294  4294 W cr_AwContents: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by brucejo75** [comment] 2019-11-25 19:22
Note: the chromium bug points to this statement in the [`WebView.destroy()`](https://developer.android.com/reference/android/webkit/WebView.html#destroy()) docs:
>This method should be called after this WebView has been removed from the view system. No other methods may be called on this WebView after destroy.

**Comment by breautek** [comment] 2019-11-26 17:40
@brucejo75 Can you provide a basic cordova app that contains **only** what is necessary to reproduce this error (ie pure cordova, no ionic or other frameworks)?
