### ISSUE TITLE
Task :app:processDebugGoogleServices FAILED

### ISSUE THREAD

**Issue by Barahten** [apache/cordova-android#1527] opened 2022-12-12 15:06 UTC
# Bug Report

## Problem
After upgrading from Cordova Android 9.1 to Cordova Android 11, the application stopped building. 

### What is expected to happen?
The application must build correctly, without errors

### What does actually happen?
Application build fails
```
Task :app:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':app:processDebugGoogleServices' (type 'GoogleServicesTask').
  - In plugin 'com.google.gms.googleservices.GoogleServicesPlugin' type 'com.google.gms.googleservices.GoogleServicesTask' field 'intermediateDir' without corresponding getter has been annotated with @OutputDirectory.
    
    Reason: Annotations on fields are only used if there's a corresponding getter for the field.
    
    Possible solutions:
      1. Add a getter for field 'intermediateDir'.
      2. Remove the annotations on 'intermediateDir'.
    
    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#ignored_annotations_on_field for more details about this problem.
  - In plugin 'com.google.gms.googleservices.GoogleServicesPlugin' type 'com.google.gms.googleservices.GoogleServicesTask' field 'packageNameXOR1' without corresponding getter has been annotated with @Input.
    
    Reason: Annotations on fields are only used if there's a corresponding getter for the field.
    
    Possible solutions:
      1. Add a getter for field 'packageNameXOR1'.
      2. Remove the annotations on 'packageNameXOR1'.
    
    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#ignored_annotations_on_field for more details about this problem.
  - In plugin 'com.google.gms.googleservices.GoogleServicesPlugin' type 'com.google.gms.googleservices.GoogleServicesTask' field 'packageNameXOR2' without corresponding getter has been annotated with @Input.
    
    Reason: Annotations on fields are only used if there's a corresponding getter for the field.
    
    Possible solutions:
      1. Add a getter for field 'packageNameXOR2'.
      2. Remove the annotations on 'packageNameXOR2'.
    
    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#ignored_annotations_on_field for more details about this problem.
  - In plugin 'com.google.gms.googleservices.GoogleServicesPlugin' type 'com.google.gms.googleservices.GoogleServicesTask' field 'quickstartFile' without corresponding getter has been annotated with @InputFile, @Optional.
    
    Reason: Annotations on fields are only used if there's a corresponding getter for the field.
    
    Possible solutions:
      1. Add a getter for field 'quickstartFile'.
      2. Remove the annotations on 'quickstartFile'.
    
    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#ignored_annotations_on_field for more details about this problem.
  - In plugin 'com.google.gms.googleservices.GoogleServicesPlugin' type 'com.google.gms.googleservices.GoogleServicesTask' field 'searchedLocation' without corresponding getter has been annotated with @Input.
    
    Reason: Annotations on fields are only used if there's a corresponding getter for the field.
    
    Possible solutions:
      1. Add a getter for field 'searchedLocation'.
      2. Remove the annotations on 'searchedLocation'.
    
    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#ignored_annotations_on_field for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
```

### Environment, Platform, Device
Android

### Version information

Plugins list:
```
cordova-android-firebase-gradle-release 4.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-open-native-settings 1.5.5 "Native settings"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-apprate 1.7.2 "AppRate"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 9.1.0-cli "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-locationservices 2.1.0 "Google Location Services for Cordova - Android"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-phone-call 1.1.3 "PhoneCall"
cordova-plugin-power-optimization 0.0.3 "PowerOptimization"
cordova-plugin-sim 1.3.3 "SIM"
cordova-plugin-speech-recognition-feat-siri 3.0.0 "Speech Recognition feat. Siri"
cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
cordova-plugin-sslcertificatechecker 6.0.0 "SSL Certificate Checker"
cordova-plugin-wkwebview-engine 1.2.2 "Cordova WKWebView Engine"
cordova-plugin-wkwebview-file-xhr 2.1.4 "Cordova WKWebView File XHR Plugin"
cordova-plugin-x-socialsharing 6.0.4 "SocialSharing"
cordova-sms-plugin 1.0.1 "Cordova SMS Plugin"
cordova-sqlite-ext 6.0.0 "Cordova sqlite storage plugin - (...) with extra features"
cordova-support-android-plugin 1.0.2 "cordova-support-android-plugin"
cordova.plugins.diagnostic 7.1.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
```
Cordova version: 11
Platform: cordova-android@11.0.0
Java: 
```
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)
```
Target SDK (targetSdk): 32
SDK Build Tool: 32.0.0
Gradle: 7.4.2
Kotlin: 1.5.31
Android Gradle Plugin (AGP): 7.2.1
Google Services Gradle Plugin: 4.3.10
AndroidX App Compat Library: 1.4.2
AndroidX WebKit Library: 1.4.0

## Information
As an attempt to solve the problem, the following resources were used:

- https://cordova.apache.org/announcements/2022/07/12/cordova-android-release-11.0.0.html
- https://volt.build/docs/android_12/
- https://ionic.zendesk.com/hc/en-us/articles/7891143965975-Migrating-to-Cordova-Android-11

None of the presented tutorials helped to fix the problem

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment] 2022-12-12 16:28
This is caused by `cordova-plugin-firebasex 9.1.0-cli "Google Firebase Plugin"`. Reproduced your issue by creating a new cordova project and adding plugins one by one while building each time, and your issue reproduced when using v9.1.0-cli of this plugin.

That plugin current version is v16.0.0, so I'll try updating it, since you're several versions behind. Using a latest version for me produces an error stating I'm missing google-services.json, which I assume will successfully build if I had an actual credentials file.

Closing as this isn't a bug with Cordova.

**Closed by breautek** 2022-12-12 16:28 UTC
