### ISSUE TITLE
Android resource linking failed (AAPT: error: resource android:attr/lStar not found)

### ISSUE THREAD

**Issue by ipehimanshu** [apache/cordova-android#1362] opened 2021-09-30 07:46 UTC
Hello 

Here is our ionic info

Ionic:

   Ionic CLI                     : 6.16.3 (C:\Users\admin\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.4.0
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 9.0.6
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 17 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : 1.4.0

System:

   NodeJS : v14.17.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.13
   OS     : Windows 10
   
 here is plugin list which we are using 
 
 com.antOnFire.camera-access 0.1 "Check access to camera on a device"
com.markveys.picture-access 0.0.1 "Check access to pictures on a device"
com.phonegap.plugins.nativesettingsopener 1.2.0 "Native settings"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-appinfo 2.1.2 "AppInfo Plugin"
cordova-plugin-calendar 5.1.5 "Calendar"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-keychain-touch-id 3.3.0 "TouchID and Keychain"
cordova-plugin-network-information 3.0.1-dev "Network Information"
cordova-plugin-printer 0.8.0 "Printer"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-universal-clipboard 0.1.0 "Clipboard"
cordova.plugins.diagnostic 6.0.2 "Diagnostic"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"

All is working fine still last day but after that it fire error when we are trying to create release build like

cordova-plugin-androidx-adapter: Processed 74 source files in 1227ms
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=undefined (DEPRECATED)
Using Android SDK: C:\Users\admin\AppData\Local\Android\sdk
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\admin\.gradle\caches\transforms-2\files-2.1\082fd8435f96aa3f026dd001121230f9\core-1.7.0-beta02\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
15 actionable tasks: 1 executed, 14 up-to-date
Command failed with exit code 1: D:\[user]\platforms\android\gradlew cdvBuildRelease -b D:\[user]\platforms\android\build.gradle
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd build android --release -- --keystore=instantautosite.keystore --ali... exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
        
  SO can you please help us
  
 Thanks

**Comment by ath0mas** [comment] 2021-09-30 10:21
Facing same issue here since today/yesterday 😢 

It seems linked to recent release of androidx.core:core 1.7-beta for android projects not yet targeting sdk 31.
Other projects like Unity faced same problem since 1.7-alpha few weeks ago : https://www.reddit.com/r/Unity3D/comments/ph2596/android_builds_fail_due_to_core170alpha02_release/

**Comment by moshe5745** [comment] 2021-09-30 12:48
Same here, is there a workaround?

**Comment by ErroKokkarda** [comment] 2021-09-30 15:03
there is a workaround but you might not like it :-D 
you create build and when files in platforms/android/app/src/build.gradle are updated
you catch just the right moment after update and before fetching of dependencies and swap

`implementation "androidx.appcompat:appcompat:+"`

with 

`implementation "androidx.appcompat:appcompat:1.3.1"`

**Comment by ath0mas** [comment] 2021-09-30 15:12
Answer by Bibzball in the Reddit I linked seems to be a good workaround ; it works fine in my case:

add a `build-extras.gradle` file with following content
```
configurations.all {
  resolutionStrategy {
    force 'androidx.core:core:1.6.0'
    force 'androidx.core:core-ktx:1.6.0'
  }
}
```

See details on using this specific file: https://cordova.apache.org/docs/en/10.x/guide/platforms/android/#extending-buildgradle

I do it with a copy of `build-extras.gradle` into `<your-project>/platforms/android/` through a script referenced as a ` src="scripts/my-copy-script.js" />` in `config.xml`.

**Comment by ipehimanshu** [comment] 2021-09-30 15:15
ok our end that issue we fixed like remove all plugin one by one 
and found 
cordova.plugins.diagnostic 6.0.2 "Diagnostic"
this is creating issue so i have installed that plugin like

ionic cordova plugin add cordova.plugins.diagnostic --variable ANDROIDX_VERSION=1.0.0 --save --verbose

then 
we need to remove platform 
ionic cordova platform rm android

and add platform like
ionic cordova platform add android@9.1.0 --save

So our end that issue solved.

**Comment by ath0mas** [comment] 2021-09-30 15:19
@ipehimanshu it is like you targeted the correct plugin ; see the issue declared in **cordova-diagnostic-plugin** https://github.com/dpa99c/cordova-diagnostic-plugin/issues/440

**Comment by ErroKokkarda** [comment] 2021-09-30 15:37
+1 for @ath0mas answer I had issue with 

appcompat
which was solved with adding 
`        <preference name="AndroidXAppCompatVersion" value="1.3.1" />`
above will force appcompat to right version
inside config.xml of ionic

and then did what ath0mas found and build is now running again 
thanks yall

**Comment by Himanshu-Mishr** [comment] 2021-10-01 08:04
issue is with `cordova-diagnostic-plugin` (PR : https://github.com/dpa99c/cordova-diagnostic-plugin/pull/441).  Solution : edit package.json

```
      "cordova.plugins.diagnostic": {
-        "ANDROIDX_VERSION": "1.+"
      },

      "cordova.plugins.diagnostic": {
+        "ANDROIDX_VERSION": "[1.0, 1.4["
      }
```
This solves it.

**Comment by dpa99c** [comment] 2021-10-01 10:16
I've published a new version of `cordpva-diagnostic-plugin` (v6.0.4) to npm which should resolve this issue.
See https://github.com/dpa99c/cordova-diagnostic-plugin/issues/440 for details.

**Comment by ipehimanshu** [comment] 2021-10-01 10:21
thank you sir

**Comment by breautek** [comment] 2021-10-03 15:00
@ipehimanshu Can you let us know if the diagnostics plugin update solves your issue and if this issue can be closed?

**Comment by tarunpahuja18** [comment] 2021-10-03 18:09
> there is a workaround but you might not like it :-D you create build and when files in platforms/android/app/src/build.gradle are updated you catch just the right moment after update and before fetching of dependencies and swap
> 
> `implementation "androidx.appcompat:appcompat:+"`
> 
> with
> 
> `implementation "androidx.appcompat:appcompat:1.3.1"`
> 
> thats best I got so far it seems someone pushed yesterday something here and stuff does not work anymore for people using ionic
> 
> https://developer.android.com/jetpack/androidx/releases/appcompat
> 
> we need to check if there is a way to avoid having to be so fast in this hand to hand cyber combat with gradle build

In case the build has to be generated from command line, there is one more place where the value of androidx.appcompat:appcompat needs to be updated which is at location

platforms/android/project.properties file

**Comment by ath0mas** [comment] 2021-10-03 19:14
In my case updating `cordova-diagnostic-plugin` to v6.0.4 solves the issue 👍 .

**Comment by breautek** [comment] 2021-10-16 02:23
Closing as won't fix / caused by third-party plugins.

`cordova-diagnostic-plugin@6.0.3` and earlier is known to have this issue, and is patched in version `6..0.4`

**Closed by breautek** 2021-10-16 02:23 UTC
