### ISSUE TITLE
cdvMinSdkVersion seems to not work in 7.1.4

### ISSUE THREAD

**Issue by falcon8823** [apache/cordova-android#599] opened 2018-12-03 16:46 UTC
I specified this `<preference name="android-minSdkVersion" value="23" />` into `config.xml`, but it seems not work in `7.1.4`.

I think these PRs might cause this problem.

- https://github.com/apache/cordova-android/pull/495/files
- https://github.com/apache/cordova-android/pull/551/files

https://github.com/apache/cordova-android/blob/a68f9fd752a25bb680da96414a3b956357c2dfcb/bin/templates/project/app/build.gradle#L125

I quickly fix this line to 
`ext.cdvMinSdkVersion = cdvMinSdkVersion == null ? null : Integer.parseInt('' + defaultMinSdkVersion)`.
It seems to work well.

I think actual `cdvMinSdkVersion` is set on this line.

https://github.com/apache/cordova-android/blob/a68f9fd752a25bb680da96414a3b956357c2dfcb/bin/templates/project/app/build.gradle#L171

**Comment by disaacson** [comment] 2018-12-04 23:04
It looks like a default value must have begun overriding that build parameter recently. I added a gradle.properties file with a `cdvMinSdkVersion=23` line and copied it to the necessary folder in a `before_build` hook like it mentions [here](https://cordova.apache.org/docs/en/latest/guide/platforms/android/#setting-gradle-properties)

**Comment by brodybits** [comment] 2018-12-05 15:47
I just added the **bug** label, will need further investigation and maybe another patch fix.

**Comment by dpogue** [comment] 2018-12-05 16:50
This problem is caused by https://github.com/apache/cordova-android/pull/495/files#diff-6e8bcecf29cf2fd3cbafdc8d406476fbR120 always setting a default minSdkVersion in gradle, which overrides whatever is specified in AndroidManifest.xml.

This is the same concern I raised in https://github.com/apache/cordova-android/issues/508

**Comment by brodybits** [comment] 2018-12-05 16:59
We may have to revert 00134cf9f3148335d17aa47dcfed589ca1460fda (cherry-pick of PR #495) in 7.1.x. For next release I think we should either resolve #508 or revert PR #495.

**Comment by dpogue** [comment] 2018-12-05 22:53
We cannot fix #508 in a patch release, and maybe not even in a minor release.

**Comment by brodybits** [comment] 2018-12-06 01:16
> We cannot fix #508 in a patch release, and maybe not even in a minor release.

Right. By "next release" I had meant "next __major__ release", just updated the comment to make it clear.

I am afraid we would have to revert the update from #495 in 7.1.x to resolve this issue in a patch release. Any better ideas?

**Comment by dmastag** [comment] 2018-12-09 09:58
Would the Solution be to move back to 7.1.3 while this is fixed ?

I recall that 7.1.4 was released just 2 days after 7.1.3 so I quickly upgraded in fear of any crippling issues

**Comment by redwolf2** [comment] 2018-12-28 13:37
@dmastag Yes, that worked for me

**Comment by brodybits** [comment] 2019-01-18 03:37
> Would the Solution be to move back to 7.1.2 while this is fixed ?

I cannot promise this will ever be fixed in a patch release. I personally do not have any extra time to make such a patch release and I think not other committers will have the extra time either.

The only way I can think of to fix this in a patch release would be to revert 00134cf (cherry-pick of PR #495) in 7.1.x. This would be a breaking change for people who configure via Gradle as described in <https://cordova.apache.org/docs/en/latest/guide/platforms/android/#setting-gradle-properties>, which would be a step backward.

For future releases such as upcoming Cordova 9 (apache/cordova#10) I would say the minimum & target SDK should be configured as described in <https://cordova.apache.org/docs/en/8.x/guide/platforms/android/#setting-gradle-properties>, not by setting the preferences in config.xml.

**Comment by falcon8823** [comment] 2019-01-18 03:47
FYI: The workaround is to specify `gradleArg` when you build.

`cordova build android -- --gradleArg=-PcdvMinSdkVersion=23`

This will override `minSdkVersion`.
I confirmed it works on `7.1.4`.

You can confirm whether it works well using `aapt` command.

`aapt l -a path/to/apk/android-release.apk | grep 'minSdkVersion'`

**Comment by robations** [comment] 2019-02-21 13:17
I'm seeing something like this after upgrading to v8 from v7.x, not sure if that's expected.

**Symptoms:**

It seems like a minimum SDK < 19 is no longer supported so I changed my preference in `config.xml`:

```
    <platform name="android">
        <preference name="android-targetSdkVersion" value="26" />
        <preference name="android-minSdkVersion" value="19" />
```

When I build (`cordova build android`) I get the following warning (which eventually causes the build to fail):

```
[Gradle Properties] Detected Gradle property "cdvMinSdkVersion" with the value of "16", Cordova's recommended value is "19"
```

When I search through the AndroidManifest.xml files under platforms/android everything is saying 19, so the merge has worked but it seems like there is a gradle property sticking around somewhere. (FYI I know almost nothing about the internals of gradle or the Android build process :-/ .)

I'm going to try @falcon8823 's workaround for now.

**Comment by eddskt** [comment] 2019-06-05 22:22
Another solution?

**Comment by eddskt** [comment] 2019-06-05 22:31
I solved changing lines in file:
platforms/android/gradle.properties

```
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m
android.useDeprecatedNdk=true
cdvMinSdkVersion=21
```

**to**

```
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m
android.useDeprecatedNdk=true
cdvMinSdkVersion=21
```

**Comment by vinayhsorathiya** [comment] 2019-06-26 11:37
@eddskt Yes, that worked for me

**Comment by breautek** [comment] 2020-04-13 03:17
Unable to reproduce this on master, I believe this was fixed by https://github.com/apache/cordova-android/pull/699

Using the `android-minSdkVersion` and checking the apk resulted in the expected min SDK to be stored.

```
aapt list -a app-debug.apk | grep SdkVersion
    A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
    A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
      A: android:minSdkVersion(0x0101020c)=(type 0x10)0x17
      A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
```

Note: The value is in hex, A: android:minSdkVersion(0x0101020c)=(type 0x10)**0x17**
0x17 is the hex value for 23.

**Closed by breautek** 2020-04-13 03:17 UTC
Labels: bug, info-needed, support
