### ISSUE TITLE
org.apache.cordova.engine.SystemWebView.mContext leak !

### ISSUE THREAD

**Issue by winnerliu** [apache/cordova-android#529] opened 2018-10-26 07:05 UTC
SystemWebView memory leak

**Comment by janpio** [comment] 2018-10-30 18:54
Can you please provide some more information?

**Comment by winnerliu** [comment] 2018-11-11 09:56
[use leakcanary found](https://i.imgur.com/6gBzMoT.png)

**Comment by winnerliu** [comment] 2018-11-11 09:57
@janpio

**Comment by brodybits** [comment] 2018-11-11 16:57
Reopening for now. @winnerliu a better explanation to walk us through the issue would be really appreciated since not all of us are familiar with Leakcanary.

**Comment by pengbs** [comment] 2019-04-28 03:41
same issue

**Comment by YauhenPaplauski** [comment] 2019-11-06 09:31
I think I have the similar(or the same) issue. 
You can reproduce it after implementing LeakCanary([link](https://square.github.io/leakcanary/getting_started/)) into your "test" project([link](https://github.com/apache/cordova-android/tree/master/test)). 
![Screenshot_2019-11-05-23-57-38-980_org apache cordova unittests](https://user-images.githubusercontent.com/22295221/68285734-e0800b80-0090-11ea-8d44-f8eb27fc9f00.png)

Also, you can enable StrictMode([link](https://developer.android.com/reference/android/os/StrictMode)) and check TestActivity(for example) on InstanceCountViolation
 - I have this error in my app and also in your "test" project. To reproduce - reenter in the activity a few times.
       ```
 StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                .detectLeakedSqlLiteObjects()
                .detectLeakedClosableObjects()
                .setClassInstanceLimit(TestActivity.class, 1)
                .penaltyLog()
//                    .penaltyDeath()
                .build());
```

**Comment by breautek** [comment] 2020-04-13 02:17
I'm unable to reproduce this (but could be using LeakCanary wrong...), but following their get started link, the logcat only produces `org.apache.cordova.unittests D/LeakCanary: Installing AppWatcher`, and nothing else. I also tried the StrictMode, but that didn't produce any output either.

Can someone confirm if this is still an issue on the current master?

**Comment by breautek** [comment] 2021-10-16 02:33
Closing due to staleness.

**Closed by breautek** 2021-10-16 02:33 UTC
Labels: info-needed, support
